version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - IMAGE_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - IMAGE_REPO_NAME="pal-mono"
      - IMAGE_URL="${IMAGE_REPO}/${IMAGE_REPO_NAME}:${BUILD_TAG}"

      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$BUILD_TAG .
      - docker tag $IMAGE_REPO_NAME:$BUILD_TAG $IMAGE_URL
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URL
      - echo Write the image definitions file...

      - CONTAINER_NAME_APP="${IMAGE_REPO_NAME}-lat-app"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_APP $IMAGE_URL > imagedefinitions_lat_app.json
      - CONTAINER_NAME_API="${IMAGE_REPO_NAME}-lat-api"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_API $IMAGE_URL > imagedefinitions_lat_api.json

      - CONTAINER_NAME_APP="${IMAGE_REPO_NAME}-stg-app"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_APP $IMAGE_URL > imagedefinitions_stg_app.json
      - CONTAINER_NAME_API="${IMAGE_REPO_NAME}-stg-api"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_API $IMAGE_URL > imagedefinitions_stg_api.json

      - CONTAINER_NAME_APP="${IMAGE_REPO_NAME}-prd-app"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_APP $IMAGE_URL > imagedefinitions_prd_app.json
      - CONTAINER_NAME_API="${IMAGE_REPO_NAME}-prd-api"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_API $IMAGE_URL > imagedefinitions_prd_api.json
artifacts:
  files:
    - imagedefinitions_lat_app.json
    - imagedefinitions_lat_api.json
    - imagedefinitions_stg_app.json
    - imagedefinitions_stg_api.json
    - imagedefinitions_prd_app.json
    - imagedefinitions_prd_api.json

cache:
  paths:
    - "/root/.docker/**/*"
