version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      - echo "Preparing to create the RELEASE_TAG..."
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date +%Y%m%d_%H%M%S)
      - RELEASE_TAG="release-${STAGE_NAME}-${TIMESTAMP}-${COMMIT_SHA}"
      - echo RELEASE_TAG $RELEASE_TAG
  build:
    commands:
      - IMAGE_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - UNIQUE_IMAGE_URL="${IMAGE_REPO}/${IMAGE_REPO_NAME}:${RELEASE_TAG}"
      - RUNTIME_IMAGE_URL="${IMAGE_REPO}/${IMAGE_REPO_NAME}:${STAGE_NAME}"

      - echo Building the Docker image...
      - export DOCKER_BUILDKIT=1
      - docker build --secret id=github_token,env=PAL_GITHUB_TOKEN -t $IMAGE_REPO_NAME:$RELEASE_TAG .
      - docker tag $IMAGE_REPO_NAME:$RELEASE_TAG $UNIQUE_IMAGE_URL
      - docker tag $IMAGE_REPO_NAME:$RELEASE_TAG $RUNTIME_IMAGE_URL
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $UNIQUE_IMAGE_URL
      - docker push $RUNTIME_IMAGE_URL
      - echo Write the image definitions file...

      - CONTAINER_NAME_API="${STAGE_NAME}-${IMAGE_REPO_NAME}-api"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_API $UNIQUE_IMAGE_URL > imagedefinitions-api.json
      - CONTAINER_NAME_MCP="${STAGE_NAME}-${IMAGE_REPO_NAME}-mcp"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_MCP $UNIQUE_IMAGE_URL > imagedefinitions-mcp.json

artifacts:
  files:
    - imagedefinitions-api.json
    - imagedefinitions-mcp.json

cache:
  paths:
    - "/root/.docker/**/*"
