[project]
name = "pal-mono"
version = "0.1.0"
requires-python = ">=3.11"
readme = "README.md"
authors = [{ name = "Proactive AI Lab", email = "rnd@proactiveailab.com" }]

dependencies = [
  # /api
  "fastapi==0.115.12",
  "uvicorn==0.30.6",
  "uvloop==0.21.0",
  "python-multipart==0.0.19",
  "httpcore==1.0.9",
  "cryptography==44.0.2",
  "stripe>=12,<13",

  # /db
  "alembic==1.13.2",
  "pgvector==0.3.2",
  "psycopg[binary]==3.2.1",
  "sqlalchemy==2.0.32",
  "asyncpg==0.30.0",

  # /ai
  "agno==1.7.2",
  "openai==1.59.9",
  "pypdf==5.1.0",
  "geopy==2.4.1",
  "pinecone==5.3.1",
  "ShopifyAPI==12.7.0",
  "ddtrace==2.21.6",
  "llama-index==0.12.28",
  "llama-index-vector-stores-pinecone==0.4.5",
  "llama-index-embeddings-cohere==0.5.1",
  "llama-index-llms-gemini==0.5.0",
  "llama-index-llms-groq==0.3.1",
  "instructor==1.7.2",
  "mem0ai==0.1.48",
  "mixpanel==4.10.1",
  "groq==0.15.0",
  "polyline==2.0.2",
  "shapely==2.1.0",
  "boto3==1.37.34",
  "datadog==0.51.0",
  "pydantic[email]==2.11.4",
  "vapi-server-sdk==1.6.0",
  "twilio==9.3.2",
  "urlextract==1.9.0",


  # DevOps
  "python-json-logger==2.0.7",
  "pytest==8.3.2",
  "pytest-mock==3.14.0",
  "pytest-cov==6.0.0",
]

[project.optional-dependencies]
dev = [
  "black==24.8.0",
  "isort==5.13.2",
  "ruff==0.6.2",
  "pyright==1.1.382",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]

# Change this value to use a different directory for the agno workspace.
# [tool.agno]
# workspace = "workspace"

[tool.black]
line-length = 88
extend-exclude = "(?x)(^|/)build/"

[tool.isort]
profile = "black"
line_length = 88
skip_glob = ["build/**"]

[tool.ruff]
extend-include = ["*.ipynb"]
exclude = ["aienv*", ".venv*", ".git", "build"]
[tool.ruff.lint.per-file-ignores]
# Ignore `F401` (import violations) in all `__init__.py` files
"__init__.py" = ["F401", "F403"]
"*.ipynb" = ["E402"]

[tool.pyright]
exclude = ["aienv*", ".venv*", "**/__pycache__", "workspace/", ".git", "build"]
typeCheckingMode = "standard"
