"""
Menu text formatting and generation for Toast integration.

This module converts structured Toast menu data into human-readable text formats
suitable for knowledge base indexing and customer-facing display.

Key responsibilities:
- Generate formatted text from Toast menu item dictionaries
- Create consistent markdown-style menu representations
- Format consolidated menu views grouped by category
- Handle both detailed (with GUIDs) and clean display formats

Output formats:
- Individual menu items with prices, descriptions, and modifiers
- Consolidated menu overviews organized by menu sections
- Clean, readable text optimized for AI processing

This module works in conjunction with _utils.py which handles the parsing
and core formatting logic for Toast-specific data structures.
"""

from typing import Dict, List


def generate_item_text(
    item_dict: Dict[str, str],
    with_ids: bool = True,
) -> str:
    """Generate text representation of a Toast menu item.

    Args:
        item_dict: Dictionary containing single key-value pair with item data
        with_ids: Whether to include GUIDs in the output (unused, kept for Adora compatibility)

    Returns:
        str: Formatted item text
    """
    # Toast items are already formatted by the parse_menu function
    # This function exists to maintain the same interface as Adora
    # Note: with_ids parameter is unused as Toast formatting is handled in _utils.parse_menu
    for _, item_text in item_dict.items():
        return item_text
    return ""


def format_consolidated_menu(
    individual_items: List[Dict[str, str]], include_customizations: bool = True
) -> str:
    """Format Toast menu items into consolidated text format.

    Args:
        individual_items: List of dictionaries where each dict contains one key-value pair
        include_customizations: Whether to include customization information (unused, kept for Adora compatibility)

    Returns:
        str: Formatted consolidated menu text

    Note:
        For Toast menus, the system prompt format is already generated by the
        parse_menu function in _utils.py. This function exists to maintain
        compatibility with the Adora interface pattern.
    """
    # For Toast, the consolidated menu is already generated in parse_menu
    # This is handled differently than Adora which needs post-processing
    # We return a simple concatenated version here for consistency

    if not individual_items:
        return ""

    # Extract and format items in a simple consolidated view
    consolidated_lines = []

    for item_dict in individual_items:
        for item_name, item_content in item_dict.items():
            # Extract basic info from the detailed content for a cleaner display
            lines = item_content.split("\n")
            if lines:
                # Get the context from second line
                context_line = lines[1] if len(lines) > 1 else ""  # Context: ...

                # Create a simplified entry
                if context_line and context_line.startswith("Context: "):
                    context = context_line.replace("Context: ", "").strip()
                    simplified_name = (
                        item_name.split(": ", 1)[-1] if ": " in item_name else item_name
                    )
                    if context:
                        consolidated_lines.append(f"{simplified_name} ({context})")
                    else:
                        consolidated_lines.append(simplified_name)
                else:
                    consolidated_lines.append(item_name)

    return "\n".join(consolidated_lines)
