"""Initialize DB

Revision ID: 038100802b26
Revises: 
Create Date: 2024-05-20 20:28:20.765299

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "038100802b26"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cognito_user_group_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("account_id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_accounts_account_id"),
        "accounts",
        ["account_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_accounts_account_id"),
        table_name="accounts",
        schema="public",
    )
    op.drop_table("accounts", schema="public")
    # ### end Alembic commands ###
