"""Initialize Database

Revision ID: 9058a93e1b40
Revises:
Create Date: 2024-08-23 08:50:07.690376

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9058a93e1b40"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_accounts_id"), "accounts", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "assistants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "raw_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["public.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_assistants_account_id"),
        "assistants",
        ["account_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_assistants_id"),
        "assistants",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "raw_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["public.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_account_id"),
        "users",
        ["account_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_id"), "users", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_conversations_id"),
        "conversations",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_conversations_user_id"),
        "conversations",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "raw_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["public.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["public.assistants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_projects_account_id"),
        "projects",
        ["account_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_projects_assistant_id"),
        "projects",
        ["assistant_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_projects_id"), "projects", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "body",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["public.conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_messages_id"), "messages", ["id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_messages_id"), table_name="messages", schema="public")
    op.drop_index(
        op.f("ix_public_messages_conversation_id"),
        table_name="messages",
        schema="public",
    )
    op.drop_table("messages", schema="public")
    op.drop_index(op.f("ix_public_projects_id"), table_name="projects", schema="public")
    op.drop_index(
        op.f("ix_public_projects_assistant_id"), table_name="projects", schema="public"
    )
    op.drop_index(
        op.f("ix_public_projects_account_id"), table_name="projects", schema="public"
    )
    op.drop_table("projects", schema="public")
    op.drop_index(
        op.f("ix_public_conversations_user_id"),
        table_name="conversations",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_conversations_id"), table_name="conversations", schema="public"
    )
    op.drop_table("conversations", schema="public")
    op.drop_index(op.f("ix_public_users_id"), table_name="users", schema="public")
    op.drop_index(
        op.f("ix_public_users_account_id"), table_name="users", schema="public"
    )
    op.drop_table("users", schema="public")
    op.drop_index(
        op.f("ix_public_assistants_id"), table_name="assistants", schema="public"
    )
    op.drop_index(
        op.f("ix_public_assistants_account_id"),
        table_name="assistants",
        schema="public",
    )
    op.drop_table("assistants", schema="public")
    op.drop_index(op.f("ix_public_accounts_id"), table_name="accounts", schema="public")
    op.drop_table("accounts", schema="public")
    # ### end Alembic commands ###
