"""add_expires_at_to_integration

Revision ID: 9a6f6f3ef3cf
Revises: 682a568fb3ef
Create Date: 2025-07-23 12:40:37.689574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a6f6f3ef3cf"
down_revision: Union[str, None] = "682a568fb3ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integration",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integration", "expires_at")
    # ### end Alembic commands ###
