"""add_account_lifecycle_statuses

Revision ID: 2a8f6caf477d
Revises: b807dd2001ca
Create Date: 2025-10-16 16:53:07.767116

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a8f6caf477d"
down_revision: Union[str, None] = "b807dd2001ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'suspended'")
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'pending_closure'")
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'closed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
