"""add project subscription table

Revision ID: 2348dc308721
Revises: 0faf49e2fb90
Create Date: 2025-07-07 01:43:56.131680

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2348dc308721"
down_revision: Union[str, None] = "0faf49e2fb90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_project_id_unique_not_deleted",
        "project_subscriptions",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("deleted = false"),
    )
    op.create_index(
        op.f("ix_project_subscriptions_id"),
        "project_subscriptions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_subscriptions_subscription_id"),
        "project_subscriptions",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_subscriptions_subscription_id"),
        table_name="project_subscriptions",
    )
    op.drop_index(
        op.f("ix_project_subscriptions_id"), table_name="project_subscriptions"
    )
    op.drop_index(
        "ix_project_id_unique_not_deleted",
        table_name="project_subscriptions",
        postgresql_where=sa.text("deleted = false"),
    )
    op.drop_table("project_subscriptions")
    # ### end Alembic commands ###
