"""Create reservations table

Revision ID: a1b2c3d4e5f6
Revises: 15b3d969c98d
Create Date: 2025-08-20 12:02:56.039321

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "15b3d969c98d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reservation_id", sa.String(), nullable=True),
        sa.Column("store_id", sa.String(), nullable=True),
        sa.Column("tracking_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "vendor",
            postgresql.ENUM(
                "yelp",
                "toast",
                "olo",
                "adora",
                "square",
                "opentable",
                name="integrationprovider",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("table_size", sa.Integer(), nullable=True),
        sa.Column("special_requests", sa.String(), nullable=True),
        sa.Column("reservation_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservations_conversation_id"),
        "reservations",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_reservations_id"), "reservations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservations_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_conversation_id"), table_name="reservations")
    op.drop_table("reservations")
    # ### end Alembic commands ###
