"""add_integration_type_and_fulfillment_strategy_to_transactions

Revision ID: 55f9526daf24
Revises: 664f7a4162ec
Create Date: 2025-08-12 18:12:49.576768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55f9526daf24"
down_revision: Union[str, None] = "664f7a4162ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "integration_type",
            sa.Enum("pos", "loyalty", "reservation", name="integrationtype"),
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("fulfillment_strategy", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "fulfillment_strategy")
    op.drop_column("transactions", "integration_type")
    # ### end Alembic commands ###
