"""add business configs to accounts

Revision ID: 056ca41ffec2
Revises: 4f42cee4276f
Create Date: 2025-03-13 05:42:19.683239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "056ca41ffec2"
down_revision: Union[str, None] = "4f42cee4276f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("business_description", sa.String(), nullable=True)
    )
    op.add_column("accounts", sa.Column("business_faq", sa.String(), nullable=True))
    op.add_column(
        "accounts", sa.Column("business_promotions", sa.String(), nullable=True)
    )
    op.add_column("accounts", sa.Column("business_catalog", sa.String(), nullable=True))
    op.add_column("accounts", sa.Column("business_others", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "business_others")
    op.drop_column("accounts", "business_catalog")
    op.drop_column("accounts", "business_promotions")
    op.drop_column("accounts", "business_faq")
    op.drop_column("accounts", "business_description")
    # ### end Alembic commands ###
