"""add stripe customer id to project table

Revision ID: 601a55cad7c1
Revises: afebadf33c4e
Create Date: 2025-12-30 16:52:42.528864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "601a55cad7c1"
down_revision: Union[str, None] = "afebadf33c4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("stripe_customer_id", sa.String(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("current_subscription_id", sa.UUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "current_subscription_id")
    op.drop_column("projects", "stripe_customer_id")
    # ### end Alembic commands ###
