"""Add secret key to integration

Revision ID: bf6c45619223
Revises: 19b630fb971a
Create Date: 2025-07-17 07:17:51.998546

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf6c45619223"
down_revision: Union[str, None] = "19b630fb971a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integration",
        sa.Column("secret_key", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integration", "secret_key")
    # ### end Alembic commands ###
