"""New Integration Tables

Revision ID: af28ec3ef995
Revises: e4a46804d792
Create Date: 2025-06-25 08:56:11.304336

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af28ec3ef995"
down_revision: Union[str, None] = "e4a46804d792"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "yelp",
                "toast",
                "olo",
                "adora",
                "square",
                name="posprovider",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "integration_type",
            sa.Enum("pos", "loyalty", "reservation", name="integrationtype"),
            nullable=False,
        ),
        sa.Column(
            "auth_type",
            sa.Enum("oauth", "client_secret", "api_key", "basic_auth", name="authtype"),
            nullable=False,
        ),
        sa.Column("business_id", sa.String(), nullable=True),
        sa.Column(
            "raw_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("client_secret", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_account_id"), "integration", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_integration_id"), "integration", ["id"], unique=False)
    op.create_table(
        "project_integration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("store_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_integration_id"), "project_integration", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_project_integration_integration_id"),
        "project_integration",
        ["integration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_integration_project_id"),
        "project_integration",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_integration_project_id"), table_name="project_integration"
    )
    op.drop_index(
        op.f("ix_project_integration_integration_id"), table_name="project_integration"
    )
    op.drop_index(op.f("ix_project_integration_id"), table_name="project_integration")
    op.drop_table("project_integration")
    op.drop_index(op.f("ix_integration_id"), table_name="integration")
    op.drop_index(op.f("ix_integration_account_id"), table_name="integration")
    op.drop_table("integration")
    op.execute("DROP TYPE IF EXISTS authtype")
    op.execute("DROP TYPE IF EXISTS integrationtype")
    # ### end Alembic commands ###
