"""add routines tables

Revision ID: afebadf33c4e
Revises: ab66d7ed80fe
Create Date: 2025-12-26 20:12:15.698870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "afebadf33c4e"
down_revision: Union[str, None] = "ab66d7ed80fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routine_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("routine_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "in_progress", "completed", "missed", name="executionstatus"
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routine_executions_routine_id"),
        "routine_executions",
        ["routine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_routine_executions_schedule_id"),
        "routine_executions",
        ["schedule_id"],
        unique=False,
    )
    op.create_table(
        "routine_item_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("routine_item_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ai_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_passed", sa.Boolean(), nullable=True),
        sa.Column("ai_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "passed", "failed", "skipped", name="itemresponsestatus"
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submission_id", "routine_item_id", name="routine_item_responses_unique_idx"
        ),
    )
    op.create_table(
        "routine_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("routine_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "input_type",
            sa.Enum("photo", name="routineinputtype"),
            server_default=sa.text("'photo'"),
            nullable=False,
        ),
        sa.Column(
            "is_required", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("reference_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "ai_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("signal_source_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routine_items_routine_id"),
        "routine_items",
        ["routine_id"],
        unique=False,
    )
    op.create_table(
        "routine_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("routine_id", sa.UUID(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "once", "daily", "weekly", "monthly", "custom", name="routinefrequency"
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=100),
            server_default=sa.text("'America/Los_Angeles'"),
            nullable=False,
        ),
        sa.Column("days_of_week", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("interval_hours", sa.Integer(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routine_schedules_routine_id"),
        "routine_schedules",
        ["routine_id"],
        unique=False,
    )
    op.create_table(
        "routine_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "submitted", "approved", "rejected", name="submissionstatus"
            ),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id"),
    )
    op.create_table(
        "routines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "opening",
                "closing",
                "food_safety",
                "cleaning",
                "compliance",
                "custom",
                name="routinecategory",
            ),
            server_default=sa.text("'custom'"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="routines_project_name_idx"),
    )
    op.create_index(
        op.f("ix_routines_project_id"), "routines", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routines_project_id"), table_name="routines")
    op.drop_table("routines")
    op.drop_table("routine_submissions")
    op.drop_index(
        op.f("ix_routine_schedules_routine_id"), table_name="routine_schedules"
    )
    op.drop_table("routine_schedules")
    op.drop_index(op.f("ix_routine_items_routine_id"), table_name="routine_items")
    op.drop_table("routine_items")
    op.drop_table("routine_item_responses")
    op.drop_index(
        op.f("ix_routine_executions_schedule_id"), table_name="routine_executions"
    )
    op.drop_index(
        op.f("ix_routine_executions_routine_id"), table_name="routine_executions"
    )
    op.drop_table("routine_executions")

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS routinecategory")
    op.execute("DROP TYPE IF EXISTS routineinputtype")
    op.execute("DROP TYPE IF EXISTS routinefrequency")
    op.execute("DROP TYPE IF EXISTS executionstatus")
    op.execute("DROP TYPE IF EXISTS submissionstatus")
    op.execute("DROP TYPE IF EXISTS itemresponsestatus")
    # ### end Alembic commands ###
