"""add_conv_type_and_customer_converted_to_conv_table

Revision ID: 72e2e172a879
Revises: 4f01b6044204
Create Date: 2025-10-17 18:11:03.213025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72e2e172a879"
down_revision: Union[str, None] = "4f01b6044204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("purpose", sa.String(), nullable=True))
    op.add_column("conversations", sa.Column("language", sa.String(), nullable=True))
    op.add_column(
        "conversations", sa.Column("ended_reason", sa.String(), nullable=True)
    )
    op.add_column(
        "conversations", sa.Column("customer_converted", sa.UUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "customer_converted")
    op.drop_column("conversations", "ended_reason")
    op.drop_column("conversations", "language")
    op.drop_column("conversations", "purpose")
    # ### end Alembic commands ###
