"""add phone numbers to orders table

Revision ID: 24e88c4e029f
Revises: 8f3a74ca9c57
Create Date: 2025-12-18 15:42:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24e88c4e029f"
down_revision: Union[str, None] = "8f3a74ca9c57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_phone_number", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("store_phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "store_phone_number")
    op.drop_column("orders", "user_phone_number")
    # ### end Alembic commands ###
