"""add_vapi_control_url_to_conversations

Revision ID: 6edddea545c9
Revises: 51f8795cf5c7
Create Date: 2025-05-27 14:00:31.026789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6edddea545c9"
down_revision: Union[str, None] = "51f8795cf5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("vapi_control_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "vapi_control_url")
    # ### end Alembic commands ###
