"""rename account column

Revision ID: 43e48ece283f
Revises: b23babcb2d15
Create Date: 2025-08-26 03:52:17.977102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43e48ece283f"
down_revision: Union[str, None] = "b23babcb2d15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("current_subscription_id", sa.UUID(), nullable=True)
    )
    op.drop_column("accounts", "stripe_subscription_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "stripe_subscription_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("accounts", "current_subscription_id")
    # ### end Alembic commands ###
