"""added transfer and links columns

Revision ID: 53fffb6c0b80
Revises: eddb96c2ba32
Create Date: 2025-08-05 16:25:07.424864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53fffb6c0b80"
down_revision: Union[str, None] = "eddb96c2ba32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("transfer_message", sa.String(), nullable=True))
    op.add_column(
        "projects", sa.Column("transfer_phone_number", sa.String(), nullable=True)
    )
    op.add_column("projects", sa.Column("reservation_link", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("ordering_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "ordering_link")
    op.drop_column("projects", "reservation_link")
    op.drop_column("projects", "transfer_phone_number")
    op.drop_column("projects", "transfer_message")
    # ### end Alembic commands ###
