"""Create orders table for external ordering platform tracking


Revision ID: abcfc2079f4a
Revises: d54854c09821
Create Date: 2025-06-17 16:07:44.421919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abcfc2079f4a"
down_revision: Union[str, None] = "d54854c09821"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_phone_number", sa.String(), nullable=False),
        sa.Column("store_phone_number", sa.String(), nullable=False),
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("tracking_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "vendor",
            sa.Enum("olo", "toast", "adora", name="order_integration_vendor"),
            nullable=True,
        ),
        sa.Column("order_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "order_number", name="uq_store_order"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders", schema="public")
    op.execute("DROP TYPE IF EXISTS order_integration_vendor")
    # ### end Alembic commands ###
