"""add stripe fields to accounts

Revision ID: 598edce233ed
Revises: 6edddea545c9
Create Date: 2025-05-28 00:15:22.721879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "598edce233ed"
down_revision: Union[str, None] = "6edddea545c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("stripe_customer_id", sa.String(), nullable=True)
    )
    op.add_column(
        "accounts", sa.Column("stripe_subscription_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "stripe_subscription_id")
    op.drop_column("accounts", "stripe_customer_id")
    # ### end Alembic commands ###
