"""Add faqs table

Revision ID: 25bd4631a878
Revises: efb4c803d4c9
Create Date: 2025-10-09 20:33:20.746539

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25bd4631a878"
down_revision: Union[str, None] = "efb4c803d4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faq_account_id"), "faq", ["account_id"], unique=False)
    op.create_index(op.f("ix_faq_id"), "faq", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faq_id"), table_name="faq")
    op.drop_index(op.f("ix_faq_account_id"), table_name="faq")
    op.drop_table("faq")
    # ### end Alembic commands ###
