"""add_page_version_table

Revision ID: 7714b4247545
Revises: c0d523a2a228
Create Date: 2025-09-15 19:48:26.276255

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7714b4247545"
down_revision: Union[str, None] = "c0d523a2a228"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("page_type", sa.String(), nullable=False),
        sa.Column("page_identifier", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_versions_id"), "page_versions", ["id"], unique=False)
    op.create_index(
        op.f("ix_page_versions_last_updated"),
        "page_versions",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_page_versions_page_identifier"),
        "page_versions",
        ["page_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_page_versions_page_type"), "page_versions", ["page_type"], unique=False
    )
    op.create_index(
        "ix_page_versions_unique",
        "page_versions",
        ["page_type", "page_identifier"],
        unique=True,
    )
    op.create_table(
        "voice_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("voice_id", sa.String(), nullable=False),
        sa.Column(
            "replacements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("first_message", sa.String(), nullable=False),
        sa.Column("transfer_message", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voice_configs_id"), "voice_configs", ["id"], unique=False)
    op.create_index(
        op.f("ix_voice_configs_project_id"),
        "voice_configs",
        ["project_id"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_voice_configs_project_id"), table_name="voice_configs")
    op.drop_index(op.f("ix_voice_configs_id"), table_name="voice_configs")
    op.drop_table("voice_configs")
    op.drop_index("ix_page_versions_unique", table_name="page_versions")
    op.drop_index(op.f("ix_page_versions_page_type"), table_name="page_versions")
    op.drop_index(op.f("ix_page_versions_page_identifier"), table_name="page_versions")
    op.drop_index(op.f("ix_page_versions_last_updated"), table_name="page_versions")
    op.drop_index(op.f("ix_page_versions_id"), table_name="page_versions")
    op.drop_table("page_versions")
    # ### end Alembic commands ###
