"""add display_name to projects

Revision ID: 36a287f00e22
Revises: 056ca41ffec2
Create Date: 2025-03-13 22:12:16.474523

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36a287f00e22"
down_revision: Union[str, None] = "056ca41ffec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("display_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "display_name")
    # ### end Alembic commands ###
