"""update_enum_values

Revision ID: bae364566e9a
Revises: e235d071beda
Create Date: 2025-06-13 06:52:50.955097

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bae364566e9a"
down_revision: Union[str, None] = "e235d071beda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'OLO' TO 'olo'")
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'TOAST' TO 'toast'")
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'ADORA' TO 'adora'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'olo' TO 'OLO'")
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'toast' TO 'TOAST'")
    op.execute("ALTER TYPE orderintegrationvendor RENAME VALUE 'adora' TO 'ADORA'")
    # ### end Alembic commands ###
