"""Redesigned prompt table

Revision ID: 19b630fb971a
Revises: bf6c45619223
Create Date: 2025-07-17 20:17:16.259419

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19b630fb971a"
down_revision: Union[str, None] = "bf6c45619223"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompts", sa.Column("default_prompt_id", sa.String(), nullable=True))
    op.drop_column("prompts", "agent_type")
    op.drop_column("prompts", "plan_tier")
    op.drop_column("prompts", "language")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompts",
        sa.Column(
            "language",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "english", "multilingual", name="agent_language", create_type=False
                )
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "prompts",
        sa.Column(
            "plan_tier",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "t1", "t2", "enterprise", name="plantier", create_type=False
                )
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "prompts",
        sa.Column(
            "agent_type",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "general", "ordering", "sales", name="agenttype", create_type=False
                )
            ),
            nullable=True,
        ),
    )

    op.drop_column("prompts", "default_prompt_id")
    # ### end Alembic commands ###
