"""create campaign tables

Revision ID: 55b7501560e7
Revises: 6c79a664061a
Create Date: 2025-05-09 00:43:47.153684

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55b7501560e7"
down_revision: Union[str, None] = "6c79a664061a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("sms", "email", "phone", name="campaignchannel"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_account_id"), "campaign", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_campaign_channel"), "campaign", ["channel"], unique=False)
    op.create_index(op.f("ix_campaign_id"), "campaign", ["id"], unique=False)
    op.create_table(
        "campaign_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "success", "failed", name="campaignmessagestatus"),
            nullable=False,
        ),
        sa.Column("error_detail", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_message_campaign_id"),
        "campaign_message",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_message_id"), "campaign_message", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_message_id"), table_name="campaign_message")
    op.drop_index(
        op.f("ix_campaign_message_campaign_id"), table_name="campaign_message"
    )
    op.drop_table("campaign_message")
    op.drop_index(op.f("ix_campaign_id"), table_name="campaign")
    op.drop_index(op.f("ix_campaign_channel"), table_name="campaign")
    op.drop_index(op.f("ix_campaign_account_id"), table_name="campaign")
    op.drop_table("campaign")
    op.execute("DROP TYPE IF EXISTS campaignchannel")
    op.execute("DROP TYPE IF EXISTS campaignmessagestatus")
    # ### end Alembic commands ###
