"""new pos integration table

Revision ID: d54854c09821
Revises: 9d73050fbd63
Create Date: 2025-06-16 14:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d54854c09821"
down_revision: Union[str, None] = "9d73050fbd63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_integration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_identifier", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("YELP", "TOAST", "OLO", "ADORA", "SQUARE", name="posprovider"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum("ACTIVATE", "INACTIVATE", name="posstate"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pos_integration_id"), "pos_integration", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pos_integration_project_id"),
        "pos_integration",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pos_integration_project_id"), table_name="pos_integration")
    op.drop_index(op.f("ix_pos_integration_id"), table_name="pos_integration")
    op.drop_table("pos_integration")
    op.execute("DROP TYPE IF EXISTS posprovider")
    op.execute("DROP TYPE IF EXISTS posstate")
    # ### end Alembic commands ###
