"""Added terms_accepted field in account schema

Revision ID: de4d38bb6f61
Revises: fca522d0a2b5
Create Date: 2025-09-10 18:50:35.320971

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de4d38bb6f61"
down_revision: Union[str, None] = "fca522d0a2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "terms_accepted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "terms_accepted")
    # ### end Alembic commands ###
