"""Added prompt and prompt details tables

Revision ID: 28ca5408086d
Revises: 2348dc308721
Create Date: 2025-07-14 18:00:22.830472

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28ca5408086d"
down_revision: Union[str, None] = "2348dc308721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "channel",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "api",
                    "instagram",
                    "internal_app",
                    "sms",
                    "voice",
                    "whatsapp",
                    name="channel",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "agent_type",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "general", "ordering", "sales", name="agenttype", create_type=False
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "plan_tier",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "t1", "t2", "enterprise", name="plantier", create_type=False
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "language",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "english", "multilingual", name="agent_language", create_type=False
                )
            ),
            nullable=True,
        ),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompts_id"), "prompts", ["id"], unique=False)
    op.create_index(
        op.f("ix_prompts_resource_id"), "prompts", ["resource_id"], unique=False
    )
    op.create_table(
        "prompt_details",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("change_summary", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prompt_id", "version_number", name="uq_prompt_version"),
    )
    op.create_index(
        op.f("ix_prompt_details_id"), "prompt_details", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_details_prompt_id"),
        "prompt_details",
        ["prompt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_details_prompt_id"), table_name="prompt_details")
    op.drop_index(op.f("ix_prompt_details_id"), table_name="prompt_details")
    op.drop_table("prompt_details")
    op.drop_index(op.f("ix_prompts_resource_id"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_id"), table_name="prompts")
    op.drop_table("prompts")
    # ### end Alembic commands ###
