"""add display_name and icon_uri to accounts

Revision ID: b2640bed44fd
Revises: d9667e980c33
Create Date: 2025-03-11 17:59:50.346435

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2640bed44fd"
down_revision: Union[str, None] = "d9667e980c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("display_name", sa.String(), nullable=True))
    op.add_column("accounts", sa.Column("icon_uri", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "icon_uri")
    op.drop_column("accounts", "display_name")
    # ### end Alembic commands ###
