"""add_t3_to_targettier_enum

Revision ID: f7962a6b6506
Revises: ffbfcfe6ad89
Create Date: 2025-10-15 14:10:08.770720

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7962a6b6506"
down_revision: Union[str, None] = "ffbfcfe6ad89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE targettier ADD VALUE IF NOT EXISTS 't3' AFTER 't2'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
