"""Rename posprovider enum to integrationprovider

Revision ID: b7c9d2e8f4a1
Revises: af28ec3ef995
Create Date: 2025-07-06 22:31:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c9d2e8f4a1"
down_revision: Union[str, None] = "af28ec3ef995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Rename the enum type from "posprovider" to "integrationprovider"
    op.execute("ALTER TYPE posprovider RENAME TO integrationprovider")

    # Update the column definition to use the new enum name
    op.execute(
        """
        ALTER TABLE integration 
        ALTER COLUMN provider TYPE integrationprovider 
        USING provider::text::integrationprovider
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert the column definition back to use the old enum name
    op.execute(
        """
        ALTER TABLE integration 
        ALTER COLUMN provider TYPE posprovider 
        USING provider::text::posprovider
    """
    )

    # Rename the enum type back from "integrationprovider" to "posprovider"
    op.execute("ALTER TYPE integrationprovider RENAME TO posprovider")

    # ### end Alembic commands ###
