"""add_affiliates_table

Revision ID: b69d5712ac47
Revises: 3d00c22ffa6c
Create Date: 2025-10-28 19:25:10.877014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b69d5712ac47"
down_revision: Union[str, None] = "3d00c22ffa6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affiliates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "rewardful_id",
            sa.String(),
            nullable=False,
            comment="UUID from Rewardful API",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_affiliates_rewardful_id"), "affiliates", ["rewardful_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_affiliates_rewardful_id"), table_name="affiliates")
    op.drop_table("affiliates")
    # ### end Alembic commands ###
