"""Add fields to subscription tables

Revision ID: 664f7a4162ec
Revises: 559a0f48fb23
Create Date: 2025-08-12 14:17:00.122002

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "664f7a4162ec"
down_revision: Union[str, None] = "559a0f48fb23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_subscriptions",
        sa.Column("stripe_product_id", sa.String(), nullable=True),
    )
    op.add_column(
        "project_subscriptions", sa.Column("call_price_id", sa.String(), nullable=True)
    )
    op.add_column(
        "project_subscriptions", sa.Column("order_price_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_subscriptions", "order_price_id")
    op.drop_column("project_subscriptions", "call_price_id")
    op.drop_column("account_subscriptions", "stripe_product_id")
    # ### end Alembic commands ###
