"""add_project_id_to_faq_table

Revision ID: 4f01b6044204
Revises: 2a8f6caf477d
Create Date: 2025-10-16 19:36:32.718025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f01b6044204"
down_revision: Union[str, None] = "2a8f6caf477d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faq", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_faq_project_id"), "faq", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faq_project_id"), table_name="faq")
    op.drop_column("faq", "project_id")
    # ### end Alembic commands ###
