"""add recurring credit grant schema for account and project subscriptions

Revision ID: 1c44c27067ad
Revises: 5b4900c9d576
Create Date: 2025-12-23 17:25:17.354750

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c44c27067ad"
down_revision: Union[str, None] = "5b4900c9d576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("account_subscription_id", sa.UUID(), nullable=True),
        sa.Column("project_subscription_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "granted", "failed", "cancelled", name="creditgrantstatus"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    sa.Enum("weekly", "monthly", "yearly", name="recurringcreditfrequency").create(
        op.get_bind(), checkfirst=True
    )

    op.add_column(
        "account_subscriptions",
        sa.Column(
            "recurring_credit_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column("recurring_credit_amount", sa.Float(), nullable=True),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column(
            "recurring_credit_frequency",
            sa.Enum("weekly", "monthly", "yearly", name="recurringcreditfrequency"),
            nullable=True,
        ),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column(
            "recurring_credit_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("recurring_credit_amount", sa.Float(), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column(
            "recurring_credit_frequency",
            sa.Enum("weekly", "monthly", "yearly", name="recurringcreditfrequency"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_subscriptions", "recurring_credit_frequency")
    op.drop_column("project_subscriptions", "recurring_credit_amount")
    op.drop_column("project_subscriptions", "recurring_credit_enabled")
    op.drop_column("account_subscriptions", "recurring_credit_frequency")
    op.drop_column("account_subscriptions", "recurring_credit_amount")
    op.drop_column("account_subscriptions", "recurring_credit_enabled")
    op.drop_table("credit_grants")
    op.execute("DROP TYPE IF EXISTS creditgrantstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS recurringcreditfrequency CASCADE")
    # ### end Alembic commands ###
