"""add project_id to conversations

Revision ID: 0f74193df451
Revises: 19b630fb971a
Create Date: 2025-07-18 06:12:40.506631

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f74193df451"
down_revision: Union[str, None] = "19b630fb971a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_conversations_project_id"),
        "conversations",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_project_id"), table_name="conversations")
    op.drop_column("conversations", "project_id")
    # ### end Alembic commands ###
