"""added timezone field to project

Revision ID: 34f79136b99c
Revises: bae364566e9a
Create Date: 2025-06-13 15:38:02.472189

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34f79136b99c"
down_revision: Union[str, None] = "bae364566e9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "timezone", sa.String(), server_default="America/Los_Angeles", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "timezone")
    # ### end Alembic commands ###
