"""add is_test to conv table

Revision ID: fca522d0a2b5
Revises: 72d513c4bfcd
Create Date: 2025-09-05 19:00:47.602281

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fca522d0a2b5"
down_revision: Union[str, None] = "72d513c4bfcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "is_test", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "is_test")
    # ### end Alembic commands ###
