"""add account status

Revision ID: 149141765ca6
Revises: 68b2e3b30b38
Create Date: 2025-05-19 19:22:55.705441

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "149141765ca6"
down_revision: Union[str, None] = "68b2e3b30b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


account_status_enum = sa.Enum(
    "active", "pending", "disabled", "deleted", name="account_status"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    account_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "accounts",
        sa.Column(
            "status", account_status_enum, server_default="active", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "status")
    op.execute("DROP TYPE IF EXISTS account_status")
    # ### end Alembic commands ###
