"""Drop External ID Unique Constraint

Revision ID: d5c53e5e6a5a
Revises: 8e5461fd725b
Create Date: 2025-06-23 19:02:51.296623

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5c53e5e6a5a"
down_revision: Union[str, None] = "8e5461fd725b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing unique index
    op.drop_index(
        "ix_account_subscriptions_external_id", table_name="account_subscriptions"
    )

    # Recreate the index without uniqueness
    op.create_index(
        op.f("ix_account_subscriptions_external_id"),
        "account_subscriptions",
        ["external_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the non-unique index
    op.drop_index(
        "ix_account_subscriptions_external_id", table_name="account_subscriptions"
    )

    # Recreate it with uniqueness
    op.create_index(
        op.f("ix_account_subscriptions_external_id"),
        "account_subscriptions",
        ["external_id"],
        unique=True,
    )
    # ### end Alembic commands ###
