"""create_catering_requests_contacts_and_project_contacts_tables

Revision ID: b807dd2001ca
Revises: f7962a6b6506
Create Date: 2025-10-16 00:46:11.242087

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b807dd2001ca"
down_revision: Union[str, None] = "f7962a6b6506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catering_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.Time(), nullable=True),
        sa.Column("event_address", sa.String(), nullable=True),
        sa.Column("event_detail", sa.Text(), nullable=True),
        sa.Column(
            "event_fulfillment",
            sa.Enum("DELIVERY", "PICKUP", name="fulfillmenttype"),
            nullable=True,
        ),
        sa.Column("contact_name", sa.String(), nullable=False),
        sa.Column("contact_phone_number", sa.String(), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CONFIRMED", "COMPLETED", "CANCELLED", name="requeststatus"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catering_requests_contact_id"),
        "catering_requests",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catering_requests_id"), "catering_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_catering_requests_project_id"),
        "catering_requests",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_table(
        "project_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "contact_id", name="uq_project_contact"),
    )
    op.create_index(
        op.f("ix_project_contacts_contact_id"),
        "project_contacts",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_contacts_id"), "project_contacts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_project_contacts_project_id"),
        "project_contacts",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_contacts_project_id"), table_name="project_contacts")
    op.drop_index(op.f("ix_project_contacts_id"), table_name="project_contacts")
    op.drop_index(op.f("ix_project_contacts_contact_id"), table_name="project_contacts")
    op.drop_table("project_contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(
        op.f("ix_catering_requests_project_id"), table_name="catering_requests"
    )
    op.drop_index(op.f("ix_catering_requests_id"), table_name="catering_requests")
    op.drop_index(
        op.f("ix_catering_requests_contact_id"), table_name="catering_requests"
    )
    op.drop_table("catering_requests")
    op.execute("DROP TYPE IF EXISTS requeststatus")
    op.execute("DROP TYPE IF EXISTS fulfillmenttype")
    # ### end Alembic commands ###
