"""remove_plan_tiere

Revision ID: 841338c6ba03
Revises: 9a6f6f3ef3cf
Create Date: 2025-07-31 05:57:58.179844

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "841338c6ba03"
down_revision: Union[str, None] = "9a6f6f3ef3cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE subscription_plans ALTER COLUMN tier TYPE targettier USING tier::text::targettier"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE subscription_plans ALTER COLUMN tier TYPE plantier USING tier::text::plantier"
    )
    # ### end Alembic commands ###
