"""add phone number and channel

Revision ID: 258c85dcd0ed
Revises: 17e0f1f55a17
Create Date: 2025-07-22 19:30:48.285526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "258c85dcd0ed"
down_revision: Union[str, None] = "17e0f1f55a17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column(
        "accounts", sa.Column("channels", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "channels")
    op.drop_column("accounts", "phone_number")
    # ### end Alembic commands ###
