"""Empty Revision


Revision ID: 02b3bdabb2e9
Revises: f3e2846498ee
Create Date: 2025-06-17 16:07:44.421919

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "02b3bdabb2e9"
down_revision: Union[str, None] = "f3e2846498ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
