"""added plan and subscription tables

Revision ID: f3e2846498ee
Revises: d54854c09821
Create Date: 2025-06-18 12:17:31.750500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3e2846498ee"
down_revision: Union[str, None] = "d54854c09821"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "tier", sa.Enum("t1", "t2", "enterprise", name="targettier"), nullable=False
        ),
        sa.Column(
            "features_included",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=True,
        ),
        sa.Column(
            "features_excluded",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=True,
        ),
        sa.Column("call_quota", sa.Integer(), nullable=True),
        sa.Column("order_quota", sa.Integer(), nullable=True),
        sa.Column("call_overage_charge", sa.Integer(), nullable=True),
        sa.Column("order_overage_charge", sa.Integer(), nullable=True),
        sa.Column("free_trial_days", sa.Integer(), nullable=True),
        sa.Column("monthly_fee", sa.Integer(), nullable=True),
        sa.Column("stripe_price_id", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_plans_id"), "subscription_plans", ["id"], unique=False
    )
    op.create_table(
        "account_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("subscription_plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "subscription_type",
            sa.Enum("trial", "monthly", "contract", name="subscriptiontype"),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("call_quota", sa.Integer(), nullable=True),
        sa.Column("order_quota", sa.Integer(), nullable=True),
        sa.Column("call_overage_charge", sa.Integer(), nullable=True),
        sa.Column("order_overage_charge", sa.Integer(), nullable=True),
        sa.Column("monthly_fee", sa.Integer(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "active", "expired", "cancelled", name="subscriptionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_subscriptions_account_id"),
        "account_subscriptions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_subscriptions_external_id"),
        "account_subscriptions",
        ["external_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_account_subscriptions_id"),
        "account_subscriptions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_subscriptions_stripe_subscription_id"),
        "account_subscriptions",
        ["stripe_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_subscriptions_subscription_plan_id"),
        "account_subscriptions",
        ["subscription_plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_subscriptions_subscription_plan_id"),
        table_name="account_subscriptions",
    )
    op.drop_index(
        op.f("ix_account_subscriptions_stripe_subscription_id"),
        table_name="account_subscriptions",
    )
    op.drop_index(
        op.f("ix_account_subscriptions_id"), table_name="account_subscriptions"
    )
    op.drop_index(
        op.f("ix_account_subscriptions_external_id"), table_name="account_subscriptions"
    )
    op.drop_index(
        op.f("ix_account_subscriptions_account_id"), table_name="account_subscriptions"
    )
    op.drop_table("account_subscriptions")
    op.drop_index(op.f("ix_subscription_plans_id"), table_name="subscription_plans")
    op.drop_table("subscription_plans")
    # ### end Alembic commands ###
