"""added language enum to agent

Revision ID: 9d73050fbd63
Revises: 34f79136b99c
Create Date: 2025-06-13 16:35:13.580820

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d73050fbd63"
down_revision: Union[str, None] = "34f79136b99c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = sa.Enum("english", "multilingual", name="agent_language")
    language_enum.create(op.get_bind())

    op.add_column(
        "agents",
        sa.Column(
            "language",
            language_enum,
            server_default="english",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "language")

    language_enum = sa.Enum("english", "multilingual", name="agent_language")
    language_enum.drop(op.get_bind())
    # ### end Alembic commands ###
