"""New account status

Revision ID: 8e5461fd725b
Revises: 2cea1b944f73
Create Date: 2025-06-21 02:07:04.092757

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e5461fd725b"
down_revision: Union[str, None] = "2cea1b944f73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'initialized'")
    op.execute(
        "ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'integration_complete'"
    )
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'evaluation_complete'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # can't delete enum values
    pass
    # ### end Alembic commands ###
