"""remove_order_integration_vendor

Revision ID: eddb96c2ba32
Revises: 841338c6ba03
Create Date: 2025-07-31 16:40:18.283119

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eddb96c2ba32"
down_revision: Union[str, None] = "841338c6ba03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS order_integration_vendor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    account_status_enum = sa.Enum(
        "olo", "toast", "adora", name="order_integration_vendor"
    )
    account_status_enum.create(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
