"""added plan and subscription to change resourse types

Revision ID: e49ee89a2acb
Revises: f4658887a491
Create Date: 2025-06-19 17:46:10.395918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e49ee89a2acb"
down_revision: Union[str, None] = "f4658887a491"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    connection.execute(
        sa.text(
            "ALTER TYPE changeresourcetype ADD VALUE IF NOT EXISTS 'SubscriptionPlan'"
        )
    )

    connection.execute(
        sa.text("ALTER TYPE changeresourcetype ADD VALUE IF NOT EXISTS 'Subscription'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
