"""remove_order_integrations

Revision ID: f4658887a491
Revises: 02b3bdabb2e9
Create Date: 2025-06-18 23:02:07.700104

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4658887a491"
down_revision: Union[str, None] = "02b3bdabb2e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_integration")
    op.execute("DROP TYPE IF EXISTS orderprotocol")
    op.execute("DROP TYPE IF EXISTS orderintegrationvendor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_integration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "protocol", sa.Enum("SMS", "POS", name="orderprotocol"), nullable=False
        ),
        sa.Column(
            "vendor",
            sa.Enum("OLO", "TOAST", "ADORA", name="orderintegrationvendor"),
            nullable=True,
        ),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
