"""Update various db tables

Revision ID: 2cea1b944f73
Revises: e49ee89a2acb
Create Date: 2025-06-20 21:57:25.126124

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cea1b944f73"
down_revision: Union[str, None] = "e49ee89a2acb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # create new enums
    plan_tier_enum = sa.Enum("t1", "t2", "enterprise", name="plantier")
    plan_tier_enum.create(op.get_bind(), checkfirst=True)

    # rename existing enum
    op.execute("ALTER TYPE posprovider RENAME 'ADORA' to 'adora'")
    op.execute("ALTER TYPE posprovider RENAME 'YELP' to 'yelp'")
    op.execute("ALTER TYPE posprovider RENAME 'TOAST' to 'toast'")
    op.execute("ALTER TYPE posprovider RENAME 'SQUARE' to 'square'")
    op.execute("ALTER TYPE posprovider RENAME 'OLO' to 'olo'")

    # alter columns
    op.drop_index("ix_accounts_lead_id", table_name="accounts")
    op.drop_column("accounts", "lead_id")
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.execute(
        "ALTER TABLE orders ALTER COLUMN vendor "
        "TYPE posprovider USING vendor::text::posprovider"
    )
    op.execute(
        "ALTER TABLE subscription_plans ALTER COLUMN tier "
        "TYPE plantier USING tier::text::plantier"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "ALTER TABLE orders ALTER COLUMN vendor "
        "TYPE order_integration_vendor USING vendor::text::order_integration_vendor"
    )
    op.execute(
        "ALTER TABLE subscription_plans ALTER COLUMN tier "
        "TYPE targettier USING tier::text::targettier"
    )

    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.add_column(
        "accounts", sa.Column("lead_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_accounts_lead_id", "accounts", ["lead_id"], unique=False)
    op.execute("DROP TYPE IF EXISTS plantier")

    op.execute("ALTER TYPE posprovider RENAME 'adora' to 'ADORA'")
    op.execute("ALTER TYPE posprovider RENAME 'yelp' to 'YELP'")
    op.execute("ALTER TYPE posprovider RENAME 'toast' to 'TOAST'")
    op.execute("ALTER TYPE posprovider RENAME 'square' to 'SQUARE'")
    op.execute("ALTER TYPE posprovider RENAME 'olo' to 'OLO'")
    # ### end Alembic commands ###
