"""Update Subscription Tables

Revision ID: 0faf49e2fb90
Revises: b7c9d2e8f4a1
Create Date: 2025-07-06 13:17:31.132730

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0faf49e2fb90"
down_revision: Union[str, None] = "b7c9d2e8f4a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method = sa.Enum("autopay", "invoice", name="paymentmethod")
    payment_method.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "account_subscriptions",
        sa.Column(
            "payment_method", payment_method, server_default="autopay", nullable=False
        ),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column("trial_start_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("account_subscriptions", "order_overage_charge")
    op.drop_column("account_subscriptions", "subscription_type")
    op.drop_column("account_subscriptions", "call_quota")
    op.drop_column("account_subscriptions", "order_quota")
    op.drop_column("account_subscriptions", "monthly_fee")
    op.drop_column("account_subscriptions", "call_overage_charge")
    op.add_column(
        "subscription_plans",
        sa.Column("hidden", sa.Boolean(), server_default="true", nullable=False),
    )

    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'deleted'")
    op.execute("DROP TYPE subscriptiontype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_type = sa.Enum("trial", "monthly", "contract", name="subscriptiontype")
    subscription_type.create(op.get_bind(), checkfirst=True)

    op.drop_column("subscription_plans", "hidden")
    op.add_column(
        "account_subscriptions",
        sa.Column(
            "call_overage_charge", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column("monthly_fee", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column("order_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column("call_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column(
            "subscription_type",
            subscription_type,
            server_default=sa.text("'trial'::subscriptiontype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "account_subscriptions",
        sa.Column(
            "order_overage_charge", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("account_subscriptions", "trial_start_date")
    op.drop_column("account_subscriptions", "payment_method")
    op.execute("DROP TYPE IF EXISTS paymentmethod")
    # ### end Alembic commands ###
