"""Add prompt to changeresourcetype

Revision ID: 682a568fb3ef
Revises: 0f74193df451
Create Date: 2025-07-21 18:58:41.771933

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "682a568fb3ef"
down_revision: Union[str, None] = "0f74193df451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    connection.execute(
        sa.text("ALTER TYPE changeresourcetype ADD VALUE IF NOT EXISTS 'Prompt'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
