"""Add docusign envelope fields in account

Revision ID: c201797270fb
Revises: b3c8d4e6a1f2
Create Date: 2025-10-01 17:03:11.569998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c201797270fb"
down_revision: Union[str, None] = "b3c8d4e6a1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("terms_envelope_id", sa.String(), nullable=True)
    )
    op.add_column(
        "accounts",
        sa.Column("terms_signed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "terms_signed_at")
    op.drop_column("accounts", "terms_envelope_id")
    # ### end Alembic commands ###
