"""add_cloned_voice_fields_to_agent_table

Revision ID: c10fab9caeb4
Revises: 4d4688aa4682
Create Date: 2025-10-20 18:59:16.256044

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c10fab9caeb4"
down_revision: Union[str, None] = "4d4688aa4682"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("cloned_voice_id", sa.String(), nullable=True))
    op.add_column(
        "agents",
        sa.Column(
            "has_voice_clone",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "has_voice_clone")
    op.drop_column("agents", "cloned_voice_id")
    # ### end Alembic commands ###
