"""update project subscription index

Revision ID: 119575fd269c
Revises: 55f9526daf24
Create Date: 2025-08-15 16:17:50.334501

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "119575fd269c"
down_revision: Union[str, None] = "55f9526daf24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_id_unique_not_deleted",
        table_name="project_subscriptions",
        postgresql_where="(deleted = false)",
    )
    op.create_index(
        "ix_project_id_subscription_id_unique_not_deleted",
        "project_subscriptions",
        ["project_id", "subscription_id"],
        unique=True,
        postgresql_where=sa.text("deleted IS false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_id_subscription_id_unique_not_deleted",
        table_name="project_subscriptions",
        postgresql_where=sa.text("deleted IS false"),
    )
    op.create_index(
        "ix_project_id_unique_not_deleted",
        "project_subscriptions",
        ["project_id"],
        unique=True,
        postgresql_where="(deleted = false)",
    )
    # ### end Alembic commands ###
