"""create phonecalls table

Revision ID: f214ca5fb318
Revises: 43e48ece283f
Create Date: 2025-08-27 20:16:43.037916

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f214ca5fb318"
down_revision: Union[str, None] = "43e48ece283f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("turn_latency_avg", sa.Float(), nullable=True),
        sa.Column("model_latency_avg", sa.Float(), nullable=True),
        sa.Column("voice_latency_avg", sa.Float(), nullable=True),
        sa.Column("transcriber_latency_avg", sa.Float(), nullable=True),
        sa.Column("endpointing_latency_avg", sa.Float(), nullable=True),
        sa.Column(
            "ended_reason",
            sa.Enum(
                "customer_ended",
                "assistant_forwarded",
                "misdialed",
                "silence_timeout",
                "max_duration_exceeded",
                "other",
                name="callendedreason",
            ),
            nullable=True,
        ),
        sa.Column(
            "call_purpose",
            sa.ARRAY(
                sa.Enum(
                    "store_info",
                    "menu_info",
                    "ordering",
                    "reservation",
                    "waitlist",
                    "takeout_issue",
                    "third_party_order",
                    "customer_service",
                    "complaint_service",
                    "complaint_food_safety",
                    "dietary_specific",
                    "lost_and_found",
                    "reservation_change",
                    "other",
                    name="callpurpose",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "user_satisfaction",
            sa.Enum("positive", "neutral", "negative", name="usersatisfaction"),
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.Enum("english", "french", "spanish", "chinese", name="calllanguage"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phone_calls_call_id"), "phone_calls", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_phone_calls_conversation_id"),
        "phone_calls",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_phone_calls_id"), "phone_calls", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phone_calls_id"), table_name="phone_calls")
    op.drop_index(op.f("ix_phone_calls_conversation_id"), table_name="phone_calls")
    op.drop_index(op.f("ix_phone_calls_call_id"), table_name="phone_calls")
    op.drop_table("phone_calls")
    # ### end Alembic commands ###
