"""Add stripe_product_id to projectsubscription table

Revision ID: 2c1b96ac2a3a
Revises: a1b2c3d4e5f6
Create Date: 2025-08-21 22:53:19.639631

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c1b96ac2a3a"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_subscriptions",
        sa.Column("stripe_product_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_subscriptions", "stripe_product_id")
    # ### end Alembic commands ###
