"""Add credit_amount to plan table

Revision ID: b23babcb2d15
Revises: 2c1b96ac2a3a
Create Date: 2025-08-22 16:26:45.535049

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b23babcb2d15"
down_revision: Union[str, None] = "2c1b96ac2a3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans", sa.Column("credit_amount", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "credit_amount")
    # ### end Alembic commands ###
