"""add_more_fields_to_lead

Revision ID: e235d071beda
Revises: d188dd3b6d6b
Create Date: 2025-06-12 17:38:25.980765

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e235d071beda"
down_revision: Union[str, None] = "d188dd3b6d6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lead", sa.Column("pos", sa.String(), nullable=True))
    op.add_column("lead", sa.Column("channels", sa.ARRAY(sa.String()), nullable=True))
    op.add_column(
        "lead",
        sa.Column(
            "contract_signed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "lead",
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_lead_contract_signed"), "lead", ["contract_signed"], unique=False
    )
    op.create_index(op.f("ix_lead_deleted"), "lead", ["deleted"], unique=False)
    op.execute("ALTER TYPE targettier RENAME VALUE 'standard' TO 't1'")
    op.execute("ALTER TYPE targettier RENAME VALUE 'premium' TO 't2'")
    op.execute("ALTER TYPE leadstatus RENAME VALUE 'converted' TO 'account_created'")
    op.execute("ALTER TYPE leadstatus ADD VALUE IF NOT EXISTS 'integration_ready'")
    op.execute("ALTER TYPE leadstatus ADD VALUE IF NOT EXISTS 'in_operation'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_deleted"), table_name="lead")
    op.drop_index(op.f("ix_lead_contract_signed"), table_name="lead")
    op.drop_column("lead", "deleted")
    op.drop_column("lead", "contract_signed")
    op.drop_column("lead", "channels")
    op.drop_column("lead", "pos")
    op.execute("ALTER TYPE targettier RENAME VALUE 't1' TO 'standard'")
    op.execute("ALTER TYPE targettier RENAME VALUE 't2' TO 'premium'")
    op.execute("ALTER TYPE leadstatus RENAME VALUE 'account_created' TO 'converted'")
    # ### end Alembic commands ###
