"""add config fields to agents

Revision ID: 4f42cee4276f
Revises: b2640bed44fd
Create Date: 2025-03-12 17:34:53.032961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f42cee4276f"
down_revision: Union[str, None] = "b2640bed44fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column("name", sa.String(), server_default="assistant", nullable=False),
    )
    op.add_column("agents", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "agents", sa.Column("communication_style", sa.String(), nullable=True)
    )
    op.add_column(
        "agents", sa.Column("interaction_guidelines", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "interaction_guidelines")
    op.drop_column("agents", "communication_style")
    op.drop_column("agents", "description")
    op.drop_column("agents", "name")
    # ### end Alembic commands ###
