"""create transactions table

Revision ID: 559a0f48fb23
Revises: 53fffb6c0b80
Create Date: 2025-08-11 19:20:26.106697

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "559a0f48fb23"
down_revision: Union[str, None] = "53fffb6c0b80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_transaction_id", sa.String(), nullable=False),
        sa.Column("external_transaction_number", sa.String(), nullable=True),
        sa.Column("store_id", sa.String(), nullable=True),
        sa.Column("tracking_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "vendor",
            postgresql.ENUM(
                "yelp",
                "toast",
                "olo",
                "adora",
                "square",
                "opentable",
                name="integrationprovider",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "order_items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("table_size", sa.Integer(), nullable=True),
        sa.Column("order_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_conversation_id"),
        "transactions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_project_id"), "transactions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_project_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_conversation_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
