"""add_onboarding_columns

Revision ID: d18476604eca
Revises: 149141765ca6
Create Date: 2025-05-25 17:15:44.373803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d18476604eca"
down_revision: Union[str, None] = "149141765ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # rename account_status to accountstatus so sqlalchemy doesn't recreate it on every migration :(
    account_status_enum = sa.Enum(
        "active", "pending", "initializing", "disabled", "deleted", name="accountstatus"
    )
    account_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "lead",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=True),
        sa.Column("business_address", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_id"), "lead", ["id"], unique=False)
    op.add_column("accounts", sa.Column("lead_id", sa.UUID(), nullable=True))
    op.execute("ALTER TABLE accounts ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "ALTER TABLE accounts ALTER COLUMN status TYPE accountstatus USING status::text::accountstatus"
    )
    op.execute("ALTER TABLE accounts ALTER COLUMN status SET DEFAULT 'active'")
    op.create_index(op.f("ix_accounts_lead_id"), "accounts", ["lead_id"], unique=False)
    op.add_column("agents", sa.Column("voice_id", sa.String(), nullable=True))
    op.add_column("agents", sa.Column("greeting_message", sa.String(), nullable=True))
    op.add_column("agents", sa.Column("voice_speed", sa.Float(), nullable=True))
    op.add_column("projects", sa.Column("store_hours", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("address", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("menu_info", sa.String(), nullable=True))
    op.add_column(
        "projects", sa.Column("service_instruction", sa.String(), nullable=True)
    )
    op.execute("DROP TYPE IF EXISTS account_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    account_status_enum = sa.Enum(
        "active", "pending", "disabled", "deleted", name="account_status"
    )
    account_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "service_instruction")
    op.drop_column("projects", "menu_info")
    op.drop_column("projects", "address")
    op.drop_column("projects", "store_hours")
    op.drop_column("agents", "voice_speed")
    op.drop_column("agents", "greeting_message")
    op.drop_column("agents", "voice_id")
    op.drop_index(op.f("ix_accounts_lead_id"), table_name="accounts")
    op.execute("ALTER TABLE accounts ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "ALTER TABLE accounts ALTER COLUMN status TYPE account_status USING status::text::account_status"
    )
    op.execute("ALTER TABLE accounts ALTER COLUMN status SET DEFAULT 'active'")
    op.execute("DROP TYPE IF EXISTS accountstatus")
    op.drop_column("accounts", "lead_id")
    op.drop_index(op.f("ix_lead_id"), table_name="lead")
    op.drop_table("lead")
    # ### end Alembic commands ###
