"""update_messages_table

Revision ID: d188dd3b6d6b
Revises: d54854c09819
Create Date: 2025-06-10 23:12:09.171270

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d188dd3b6d6b"
down_revision: Union[str, None] = "d54854c09819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_messages_conversation_created_at",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_conversation_created_at", table_name="messages")
    # ### end Alembic commands ###
