"""Remove stripe_price_id from subscription_plans table

Revision ID: 15b3d969c98d
Revises: f3a4b5c6d7e8
Create Date: 2025-08-20 14:55:18.687913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b3d969c98d"
down_revision: Union[str, None] = "f3a4b5c6d7e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "stripe_price_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans",
        sa.Column("stripe_price_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
