"""add lead columns to accounts table

Revision ID: 17e0f1f55a17
Revises: 682a568fb3ef
Create Date: 2025-07-22 00:48:47.236462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17e0f1f55a17"
down_revision: Union[str, None] = "682a568fb3ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("owner", sa.String(), nullable=True))
    op.add_column(
        "accounts",
        sa.Column(
            "segment",
            sa.Enum("smb", "mm", "ent", name="businesssegment"),
            nullable=True,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "tier", sa.Enum("t1", "t2", "enterprise", name="targettier"), nullable=True
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "contract_signed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("accounts", sa.Column("notes", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_accounts_contract_signed"),
        "accounts",
        ["contract_signed"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_contract_signed"), table_name="accounts")
    op.drop_column("accounts", "notes")
    op.drop_column("accounts", "contract_signed")
    op.drop_column("accounts", "tier")
    op.drop_column("accounts", "segment")
    op.drop_column("accounts", "owner")
    # ### end Alembic commands ###
