"""new order integration table

Revision ID: d54854c09819
Revises: 867cef7860c1
Create Date: 2025-05-30 05:22:11.877087

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d54854c09819"
down_revision: Union[str, None] = "867cef7860c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_integration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "protocol", sa.Enum("SMS", "POS", name="orderprotocol"), nullable=False
        ),
        sa.Column(
            "vendor",
            sa.Enum("OLO", "TOAST", "ADORA", name="orderintegrationvendor"),
            nullable=True,
        ),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_integration_account_id"),
        "order_integration",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_integration_id"), "order_integration", ["id"], unique=False
    )
    op.add_column(
        "projects", sa.Column("order_integration_id", sa.UUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "order_integration_id")
    op.drop_index(op.f("ix_order_integration_id"), table_name="order_integration")
    op.drop_index(
        op.f("ix_order_integration_account_id"), table_name="order_integration"
    )
    op.drop_table("order_integration")
    op.execute("DROP TYPE IF EXISTS orderprotocol")
    op.execute("DROP TYPE IF EXISTS orderintegrationvendor")
    # ### end Alembic commands ###
