"""add checklist table

Revision ID: 3d00c22ffa6c
Revises: f1c61f61346e
Create Date: 2025-10-23 08:29:51.862678

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d00c22ffa6c"
down_revision: Union[str, None] = "f1c61f61346e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update the existing checkstatus enum to match the new CheckStatus definition
    # Remove 'expired' and add 'error' and 'overdue'
    connection = op.get_bind()

    # Add new enum values if they don't exist
    connection.execute(
        sa.text("ALTER TYPE checkstatus ADD VALUE IF NOT EXISTS 'error'")
    )
    connection.execute(
        sa.text("ALTER TYPE checkstatus ADD VALUE IF NOT EXISTS 'overdue'")
    )

    # Note: We cannot easily remove 'expired' without dropping and recreating the type
    # If it's not being used, we can leave it for backwards compatibility

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "ai_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checklists_id"), "checklists", ["id"], unique=False)
    op.create_index(
        op.f("ix_checklists_project_id"), "checklists", ["project_id"], unique=False
    )

    # Rename checkpoint_results to checkpoint_runs and add new columns
    op.rename_table("checkpoint_results", "checkpoint_runs")

    # Add new columns to the renamed table
    op.add_column("checkpoint_runs", sa.Column("review", sa.String(), nullable=True))
    op.add_column("checkpoint_runs", sa.Column("reviewer", sa.String(), nullable=True))
    op.add_column(
        "checkpoint_runs",
        sa.Column(
            "is_reviewed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )

    # Rename indexes from checkpoint_results to checkpoint_runs
    op.execute(
        "ALTER INDEX ix_checkpoint_results_checkpoint_id RENAME TO ix_checkpoint_runs_checkpoint_id"
    )
    op.execute("ALTER INDEX ix_checkpoint_results_id RENAME TO ix_checkpoint_runs_id")
    op.execute(
        "ALTER INDEX ix_checkpoint_results_status RENAME TO ix_checkpoint_runs_status"
    )
    op.execute(
        "ALTER INDEX ix_checkpoint_results_submission_id RENAME TO ix_checkpoint_runs_submission_id"
    )

    # Create the new created_at index (checkpoint_results already has created_at column)
    op.create_index(
        op.f("ix_checkpoint_runs_created_at"),
        "checkpoint_runs",
        ["created_at"],
        unique=False,
    )

    # Add checklist_id as nullable first, then populate with random UUIDs for existing rows
    op.add_column("checkpoints", sa.Column("checklist_id", sa.UUID(), nullable=True))

    # Assign random UUIDs to existing checkpoints
    connection.execute(
        sa.text(
            "UPDATE checkpoints SET checklist_id = gen_random_uuid() WHERE checklist_id IS NULL"
        )
    )

    # Now make the column NOT NULL
    op.alter_column("checkpoints", "checklist_id", nullable=False)
    op.add_column(
        "checkpoints",
        sa.Column(
            "requires_image",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "checkpoints",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "checkpoints",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_checkpoints_checklist_id"),
        "checkpoints",
        ["checklist_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checkpoints_checklist_id"), table_name="checkpoints")
    op.drop_column("checkpoints", "updated_at")
    op.drop_column("checkpoints", "created_at")
    op.drop_column("checkpoints", "requires_image")
    op.drop_column("checkpoints", "checklist_id")

    # Drop the created_at index that was added
    op.drop_index(
        op.f("ix_checkpoint_runs_created_at"),
        table_name="checkpoint_runs",
    )

    # Rename indexes back from checkpoint_runs to checkpoint_results
    op.execute(
        "ALTER INDEX ix_checkpoint_runs_checkpoint_id RENAME TO ix_checkpoint_results_checkpoint_id"
    )
    op.execute("ALTER INDEX ix_checkpoint_runs_id RENAME TO ix_checkpoint_results_id")
    op.execute(
        "ALTER INDEX ix_checkpoint_runs_status RENAME TO ix_checkpoint_results_status"
    )
    op.execute(
        "ALTER INDEX ix_checkpoint_runs_submission_id RENAME TO ix_checkpoint_results_submission_id"
    )

    # Drop the new columns
    op.drop_column("checkpoint_runs", "is_reviewed")
    op.drop_column("checkpoint_runs", "reviewer")
    op.drop_column("checkpoint_runs", "review")

    # Rename table back to checkpoint_results
    op.rename_table("checkpoint_runs", "checkpoint_results")

    op.drop_index(op.f("ix_checklists_project_id"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_id"), table_name="checklists")
    op.drop_table("checklists")
    # ### end Alembic commands ###
