"""add memory_enabled column to agents table

Revision ID: efb4c803d4c9
Revises: 188f23c10d61
Create Date: 2025-10-09 13:15:19.773717

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efb4c803d4c9"
down_revision: Union[str, None] = "188f23c10d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "memory_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "memory_enabled")
    # ### end Alembic commands ###
