"""rename menu_info and voice_speed

Revision ID: 51f8795cf5c7
Revises: d18476604eca
Create Date: 2025-05-26 21:15:39.447701

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51f8795cf5c7"
down_revision: Union[str, None] = "d18476604eca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    speech_rate_enum = sa.Enum(
        "slowest", "slower", "normal", "faster", "fastest", name="speechrate"
    )
    speech_rate_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "agents",
        sa.Column(
            "speech_rate",
            speech_rate_enum,
            server_default="normal",
            nullable=False,
        ),
    )
    op.drop_column("agents", "voice_speed")
    op.add_column("projects", sa.Column("product_info", sa.String(), nullable=True))
    op.drop_column("projects", "menu_info")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("menu_info", sa.String(), nullable=True),
    )
    op.drop_column("projects", "product_info")
    op.add_column(
        "agents",
        sa.Column(
            "voice_speed",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("agents", "speech_rate")
    # ### end Alembic commands ###
