"""create change log tables

Revision ID: 8f55a8c5d0ad
Revises: 4a0fe4ba551c
Create Date: 2025-05-13 21:59:49.347952

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f55a8c5d0ad"
down_revision: Union[str, None] = "4a0fe4ba551c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum("Account", "Agent", "Project", name="changeresourcetype"),
            nullable=False,
        ),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("Update", "Create", "Delete", name="changeaction"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_log_account_id"), "change_log", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_change_log_id"), "change_log", ["id"], unique=False)
    op.create_table(
        "change_field",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("change_log_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_log_id"],
            ["change_log.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_field_change_log_id"),
        "change_field",
        ["change_log_id"],
        unique=False,
    )
    op.create_index(op.f("ix_change_field_id"), "change_field", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_change_field_id"), table_name="change_field")
    op.drop_index(op.f("ix_change_field_change_log_id"), table_name="change_field")
    op.drop_table("change_field")
    op.drop_index(op.f("ix_change_log_id"), table_name="change_log")
    op.drop_index(op.f("ix_change_log_account_id"), table_name="change_log")
    op.drop_table("change_log")
    op.execute("DROP TYPE IF EXISTS changeaction")
    op.execute("DROP TYPE IF EXISTS changeresourcetype")
    # ### end Alembic commands ###
