"""add_cloned_voice_fields_to_voice_config_table

Revision ID: f1c61f61346e
Revises: c10fab9caeb4
Create Date: 2025-10-21 21:15:13.408461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1c61f61346e"
down_revision: Union[str, None] = "c10fab9caeb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_configs", sa.Column("cloned_voice_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_configs", "cloned_voice_id")
    # ### end Alembic commands ###
