"""rename state enum

Revision ID: e4a46804d792
Revises: d5c53e5e6a5a
Create Date: 2025-06-24 16:42:28.438679

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4a46804d792"
down_revision: Union[str, None] = "d5c53e5e6a5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE posstate RENAME VALUE 'ACTIVATE' TO 'active'")
    op.execute("ALTER TYPE posstate RENAME VALUE 'INACTIVATE' TO 'inactive'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE posstate RENAME VALUE 'active' TO 'ACTIVATE'")
    op.execute("ALTER TYPE posstate RENAME VALUE 'inactive' TO 'INACTIVATE'")
    # ### end Alembic commands ###
