"""add industry to accounts

Revision ID: 6c79a664061a
Revises: 36a287f00e22
Create Date: 2025-03-28 23:07:40.663763

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c79a664061a"
down_revision: Union[str, None] = "36a287f00e22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("industry", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "industry")
    # ### end Alembic commands ###
