"""add_more_fields_to_lead

Revision ID: a50558cd47b4
Revises: d54854c09819
Create Date: 2025-06-10 16:26:53.094420

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50558cd47b4"
down_revision: Union[str, None] = "d54854c09819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    business_segment_enum = sa.Enum("smb", "mm", "ent", name="businesssegment")
    business_segment_enum.create(op.get_bind(), checkfirst=True)
    target_tier_enum = sa.Enum("standard", "premium", "enterprise", name="targettier")
    target_tier_enum.create(op.get_bind(), checkfirst=True)
    lead_status_enum = sa.Enum("pending", "converted", name="leadstatus")
    lead_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lead", sa.Column("logo_uri", sa.String(), nullable=True))
    op.add_column("lead", sa.Column("segment", business_segment_enum, nullable=True))
    op.add_column("lead", sa.Column("tier", target_tier_enum, nullable=True))
    op.add_column("lead", sa.Column("account_id", sa.UUID(), nullable=True))
    op.add_column("lead", sa.Column("owner", sa.String(), nullable=True))
    op.add_column("lead", sa.Column("hubspot_record_id", sa.String(), nullable=True))
    op.add_column(
        "lead",
        sa.Column("status", lead_status_enum, server_default="pending", nullable=False),
    )
    op.add_column("lead", sa.Column("notes", sa.String(), nullable=True))
    op.add_column(
        "lead",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead", "updated_at")
    op.drop_column("lead", "notes")
    op.drop_column("lead", "status")
    op.drop_column("lead", "hubspot_record_id")
    op.drop_column("lead", "owner")
    op.drop_column("lead", "account_id")
    op.drop_column("lead", "tier")
    op.drop_column("lead", "segment")
    op.drop_column("lead", "logo_uri")
    op.execute("DROP TYPE IF EXISTS leadstatus")
    op.execute("DROP TYPE IF EXISTS targettier")
    op.execute("DROP TYPE IF EXISTS businesssegment")
    # ### end Alembic commands ###
