"""add base price id to project subscription

Revision ID: 01b994cecb12
Revises: e2102dc11719
Create Date: 2025-08-19 17:18:31.670696

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01b994cecb12"
down_revision: Union[str, None] = "e2102dc11719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_subscriptions", sa.Column("base_price_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_subscriptions", "base_price_id")
    # ### end Alembic commands ###
