"""add notification preferences to accounts

Revision ID: 8f3a74ca9c57
Revises: d0cf4b215638
Create Date: 2025-12-04 22:51:35.502599

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f3a74ca9c57"
down_revision: Union[str, None] = "d0cf4b215638"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "notification_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{\"email_enabled\": true}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "accounts", sa.Column("notification_email", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "notification_email")
    op.drop_column("accounts", "notification_preferences")
    # ### end Alembic commands ###
