"""Add features table for gatekeeper service

Revision ID: f1a70b9150fb
Revises: 4937ffff306a
Create Date: 2026-01-10 15:28:24.582571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a70b9150fb"
down_revision: Union[str, None] = "4937ffff306a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feature", sa.String(), nullable=False),
        sa.Column(
            "identifier_type",
            sa.Enum("agent", "account", "project", "user", name="identifiertype"),
            nullable=False,
        ),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identifier_type", "identifier", "feature", name="uq_feature_identifier"
        ),
    )
    op.create_index(op.f("ix_features_feature"), "features", ["feature"], unique=False)
    op.create_index(op.f("ix_features_id"), "features", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_features_id"), table_name="features")
    op.drop_index(op.f("ix_features_feature"), table_name="features")
    op.drop_table("features")
    # ### end Alembic commands ###
