"""add call quality fields to phone calls

Revision ID: f2fc2243cb69
Revises: 3fa8e1aa036a
Create Date: 2026-06-23 05:33:24.271793

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2fc2243cb69"
down_revision: Union[str, None] = "3fa8e1aa036a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _call_quality_label_enum() -> sa.Enum:
    return sa.Enum(
        "legitimate_restaurant_call",
        "robot_prerecorded",
        "promotional_sales",
        "spam_scam",
        "prank_or_abusive",
        "unknown_unclear",
        name="callqualitylabel",
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    call_quality_label_enum = _call_quality_label_enum()
    call_quality_label_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "phone_calls",
        sa.Column("call_quality_label", call_quality_label_enum, nullable=True),
    )
    op.add_column(
        "phone_calls",
        sa.Column("call_quality_reason_codes", sa.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone_calls", "call_quality_reason_codes")
    op.drop_column("phone_calls", "call_quality_label")
    _call_quality_label_enum().drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
