"""capability_and_action

Revision ID: f78ec1478965
Revises: 601a55cad7c1
Create Date: 2026-01-03 09:52:06.384694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f78ec1478965"
down_revision: Union[str, None] = "601a55cad7c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("capability_identifier", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "capability_identifier", name="uq_agent_capability"
        ),
    )
    op.create_index(
        op.f("ix_agent_capabilities_agent_id"),
        "agent_capabilities",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_capabilities_capability_identifier"),
        "agent_capabilities",
        ["capability_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_capabilities_id"), "agent_capabilities", ["id"], unique=False
    )
    op.create_table(
        "capability_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_capability_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False, server_default="ALL"),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_capability_id",
            "action",
            "channel",
            name="uq_capability_action_channel",
        ),
    )
    op.create_index(
        op.f("ix_capability_actions_action"),
        "capability_actions",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_actions_agent_capability_id"),
        "capability_actions",
        ["agent_capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_actions_channel"),
        "capability_actions",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_actions_id"), "capability_actions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_capability_actions_id"), table_name="capability_actions")
    op.drop_index(
        op.f("ix_capability_actions_channel"), table_name="capability_actions"
    )
    op.drop_index(
        op.f("ix_capability_actions_agent_capability_id"),
        table_name="capability_actions",
    )
    op.drop_index(op.f("ix_capability_actions_action"), table_name="capability_actions")
    op.drop_table("capability_actions")
    op.drop_index(op.f("ix_agent_capabilities_id"), table_name="agent_capabilities")
    op.drop_index(
        op.f("ix_agent_capabilities_capability_identifier"),
        table_name="agent_capabilities",
    )
    op.drop_index(
        op.f("ix_agent_capabilities_agent_id"), table_name="agent_capabilities"
    )
    op.drop_table("agent_capabilities")
    # ### end Alembic commands ###
