"""make catering request lead fields nullable

Revision ID: 4caa090da0f5
Revises: 20cb36ab46c9
Create Date: 2026-06-08 21:24:32.867299

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4caa090da0f5"
down_revision: Union[str, None] = "20cb36ab46c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catering_requests",
        sa.Column("contact_email", sa.String(), nullable=True),
    )
    op.alter_column(
        "catering_requests",
        "event_date",
        existing_type=sa.DATE(),
        nullable=True,
    )
    op.alter_column(
        "catering_requests",
        "contact_phone_number",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "catering_requests",
        "contact_phone_number",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "catering_requests",
        "event_date",
        existing_type=sa.DATE(),
        nullable=False,
    )
    op.drop_column("catering_requests", "contact_email")
    # ### end Alembic commands ###
