"""add_stripe_coupon_id_to_account_and_project_tables

Revision ID: 13262616703e
Revises: d8e3dc647178
Create Date: 2026-01-07 18:40:07.876266

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13262616703e"
down_revision: Union[str, None] = "d8e3dc647178"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("stripe_coupon_id", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("stripe_coupon_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "stripe_coupon_id")
    op.drop_column("accounts", "stripe_coupon_id")
    # ### end Alembic commands ###
