"""Create onboarding_webhook_events table

Revision ID: 8fc3bde5c547
Revises: 46d39b27145b
Create Date: 2026-02-09 17:23:29.468129

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8fc3bde5c547"
down_revision: Union[str, None] = "46d39b27145b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("src", sa.String(), nullable=False),
        sa.Column("restaurant_guid", sa.String(), nullable=False),
        sa.Column("created_by_first_name", sa.String(), nullable=True),
        sa.Column("created_by_last_name", sa.String(), nullable=True),
        sa.Column("created_by_email_address", sa.String(), nullable=True),
        sa.Column("created_by_phone_number", sa.String(), nullable=True),
        sa.Column("restaurant_phone_number", sa.String(), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "onboarding_status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="onboardingstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_webhook_events_account_id"),
        "onboarding_webhook_events",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_webhook_events_created_at"),
        "onboarding_webhook_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_webhook_events_project_id"),
        "onboarding_webhook_events",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_webhook_events_restaurant_guid"),
        "onboarding_webhook_events",
        ["restaurant_guid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_onboarding_webhook_events_restaurant_guid"),
        table_name="onboarding_webhook_events",
    )
    op.drop_index(
        op.f("ix_onboarding_webhook_events_project_id"),
        table_name="onboarding_webhook_events",
    )
    op.drop_index(
        op.f("ix_onboarding_webhook_events_created_at"),
        table_name="onboarding_webhook_events",
    )
    op.drop_index(
        op.f("ix_onboarding_webhook_events_account_id"),
        table_name="onboarding_webhook_events",
    )
    op.drop_table("onboarding_webhook_events")
    op.execute("DROP TYPE IF EXISTS onboardingstatus")
    # ### end Alembic commands ###
