"""add catering request financial history fields

Revision ID: b7f43f8aac6e
Revises: f2b5c6a7d8e9
Create Date: 2026-06-10 23:16:58.276329

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7f43f8aac6e"
down_revision: Union[str, None] = "f2b5c6a7d8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catering_requests",
        sa.Column(
            "prior_catering_request_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "prior_order_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "last_catering_request_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "estimated_order_value",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "confirmed_order_value",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "deposit_requirement_value",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "catering_requests",
        sa.Column(
            "deposit_received_value",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catering_requests", "deposit_received_value")
    op.drop_column("catering_requests", "deposit_requirement_value")
    op.drop_column("catering_requests", "confirmed_order_value")
    op.drop_column("catering_requests", "estimated_order_value")
    op.drop_column("catering_requests", "last_order_at")
    op.drop_column("catering_requests", "last_catering_request_at")
    op.drop_column("catering_requests", "prior_order_count")
    op.drop_column("catering_requests", "prior_catering_request_count")
    # ### end Alembic commands ###
