"""Add tos_acceptances table

Revision ID: 46d39b27145b
Revises: bb7b1bd7d01a
Create Date: 2026-01-29 19:38:01.418286

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46d39b27145b"
down_revision: Union[str, None] = "bb7b1bd7d01a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tos_acceptances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("tos_version", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "tos_version", name="uq_tos_acceptances_account_version"
        ),
    )
    op.create_index(
        "ix_tos_acceptances_account_id", "tos_acceptances", ["account_id"], unique=False
    )
    op.create_index(
        "ix_tos_acceptances_user_id", "tos_acceptances", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tos_acceptances_user_id", table_name="tos_acceptances", if_exists=True
    )
    op.drop_index(
        "ix_tos_acceptances_account_id", table_name="tos_acceptances", if_exists=True
    )
    op.drop_table("tos_acceptances")
    # ### end Alembic commands ###
