"""added author_name to feedback table

Revision ID: 58a96ada96f2
Revises: f1a70b9150fb
Create Date: 2026-01-14 16:23:48.395454

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a96ada96f2"
down_revision: Union[str, None] = "f1a70b9150fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feedback", sa.Column("author_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "author_name")
    # ### end Alembic commands ###
