"""add fields from account subscription to project

Revision ID: e3b4fce055cc
Revises: f78ec1478965
Create Date: 2026-01-05 13:28:15.911201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3b4fce055cc"
down_revision: Union[str, None] = "f78ec1478965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_subscriptions", sa.Column("external_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("version", sa.Integer(), server_default="1", nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("subscription_plan_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column(
            "payment_method",
            sa.Enum("autopay", "invoice", name="paymentmethod"),
            server_default="autopay",
            nullable=True,
        ),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("trial_start_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "project_subscriptions",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "expired",
                "cancelled",
                "trialing",
                "past_due",
                "unpaid",
                "deleted",
                name="subscriptionstatus",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_subscriptions", "status")
    op.drop_column("project_subscriptions", "end_date")
    op.drop_column("project_subscriptions", "start_date")
    op.drop_column("project_subscriptions", "trial_start_date")
    op.drop_column("project_subscriptions", "payment_method")
    op.drop_column("project_subscriptions", "stripe_subscription_id")
    op.drop_column("project_subscriptions", "subscription_plan_id")
    op.drop_column("project_subscriptions", "version")
    op.drop_column("project_subscriptions", "external_id")
    # ### end Alembic commands ###
