"""drop terms columns from accounts table

Revision ID: 1e67b46a4933
Revises: 9af2adc8dfe2
Create Date: 2026-03-12 20:37:57.078549

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e67b46a4933"
down_revision: Union[str, None] = "9af2adc8dfe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "terms_signed_at")
    op.drop_column("accounts", "terms_envelope_id")
    op.drop_column("accounts", "terms_accepted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "terms_accepted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "terms_envelope_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "terms_signed_at",
            sa.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
