"""add transfer reason fields to phone calls

Revision ID: d27a86f44484
Revises: d3b0731aa483
Create Date: 2026-06-03 19:04:39.872794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d27a86f44484"
down_revision: Union[str, None] = "d3b0731aa483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phone_calls", sa.Column("transfer_reason_category", sa.String(), nullable=True)
    )
    op.add_column(
        "phone_calls",
        sa.Column("transfer_agent_was_at_fault", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone_calls", "transfer_agent_was_at_fault")
    op.drop_column("phone_calls", "transfer_reason_category")
    # ### end Alembic commands ###
