"""add catering menus table

Revision ID: a4d9c8e7b6a5
Revises: 9d7e1f4a6b2c
Create Date: 2026-06-16 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d9c8e7b6a5"
down_revision: Union[str, None] = "9d7e1f4a6b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catering_menus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("item_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catering_menus_account_id"),
        "catering_menus",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catering_menus_id"),
        "catering_menus",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catering_menus_project_id"),
        "catering_menus",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_catering_menus_project_id"), table_name="catering_menus")
    op.drop_index(op.f("ix_catering_menus_id"), table_name="catering_menus")
    op.drop_index(op.f("ix_catering_menus_account_id"), table_name="catering_menus")
    op.drop_table("catering_menus")
    # ### end Alembic commands ###
