"""Add agent_type field

Revision ID: 32d846ce185f
Revises: c72452ac6812
Create Date: 2025-05-15 23:54:02.692922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from api.schemas.admin.agent import AgentType

# revision identifiers, used by Alembic.
revision: str = "32d846ce185f"
down_revision: Union[str, None] = "c72452ac6812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "agent_type",
            sa.Enum(AgentType),
            server_default=AgentType.GENERAL.value,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "agent_type")
    # ### end Alembic commands ###
