"""Remove campaign table fk

Revision ID: 4a0fe4ba551c
Revises: 55b7501560e7
Create Date: 2025-05-09 02:17:00.762151

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a0fe4ba551c"
down_revision: Union[str, None] = "55b7501560e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "campaign_message_campaign_id_fkey", "campaign_message", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "campaign_message_campaign_id_fkey",
        "campaign_message",
        "campaign",
        ["campaign_id"],
        ["id"],
    )
    # ### end Alembic commands ###
