"""add agent_type to agents

Revision ID: 68b2e3b30b38
Revises: c72452ac6812
Create Date: 2025-05-16 23:37:59.819658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68b2e3b30b38"
down_revision: Union[str, None] = "c72452ac6812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

agent_type_enum = sa.Enum("general", "ordering", "sales", name="agenttype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    agent_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "agents",
        sa.Column(
            "agent_type", agent_type_enum, server_default="general", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "agent_type")
    # ### end Alembic commands ###
