"""reset idx and fk names

Revision ID: d9667e980c33
Revises: fab2f7629718
Create Date: 2025-03-06 01:19:24.134713

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9667e980c33"
down_revision: Union[str, None] = "fab2f7629718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_public_accounts_id", table_name="accounts")
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.drop_index("ix_public_agents_account_id", table_name="agents")
    op.drop_index("ix_public_agents_id", table_name="agents")
    op.create_index(
        op.f("ix_agents_account_id"), "agents", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.drop_index("ix_public_conversations_id", table_name="conversations")
    op.drop_index("ix_public_conversations_user_id", table_name="conversations")
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.drop_index("ix_public_feedback_id", table_name="feedback")
    op.drop_index("ix_public_feedback_message_id", table_name="feedback")
    op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
    op.create_index(
        op.f("ix_feedback_message_id"), "feedback", ["message_id"], unique=False
    )
    op.drop_index("ix_public_messages_conversation_id", table_name="messages")
    op.drop_index("ix_public_messages_id", table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.drop_index("ix_public_projects_account_id", table_name="projects")
    op.drop_index("ix_public_projects_agent_id", table_name="projects")
    op.drop_index("ix_public_projects_id", table_name="projects")
    op.create_index(
        op.f("ix_projects_account_id"), "projects", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_agent_id"), "projects", ["agent_id"], unique=False
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.drop_index("ix_public_users_account_id", table_name="users")
    op.drop_index("ix_public_users_id", table_name="users")
    op.create_index(op.f("ix_users_account_id"), "users", ["account_id"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_account_id"), table_name="users")
    op.create_index("ix_public_users_id", "users", ["id"], unique=False)
    op.create_index("ix_public_users_account_id", "users", ["account_id"], unique=False)
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_agent_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_account_id"), table_name="projects")
    op.create_index("ix_public_projects_id", "projects", ["id"], unique=False)
    op.create_index(
        "ix_public_projects_agent_id", "projects", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_public_projects_account_id", "projects", ["account_id"], unique=False
    )
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.create_index("ix_public_messages_id", "messages", ["id"], unique=False)
    op.create_index(
        "ix_public_messages_conversation_id",
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_feedback_message_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
    op.create_index(
        "ix_public_feedback_message_id", "feedback", ["message_id"], unique=False
    )
    op.create_index("ix_public_feedback_id", "feedback", ["id"], unique=False)
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.create_index(
        "ix_public_conversations_user_id", "conversations", ["user_id"], unique=False
    )
    op.create_index("ix_public_conversations_id", "conversations", ["id"], unique=False)
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_account_id"), table_name="agents")
    op.create_index("ix_public_agents_id", "agents", ["id"], unique=False)
    op.create_index(
        "ix_public_agents_account_id", "agents", ["account_id"], unique=False
    )
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.create_index("ix_public_accounts_id", "accounts", ["id"], unique=False)
    # ### end Alembic commands ###
