#!/bin/bash

############################################################################
#
# Install python dependencies. Run this inside a virtual env.
# Usage:
# 1. Create + activate virtual env using:
#     python3 -m venv aienv
#     source aienv/bin/activate
# 2. Install workspace and dependencies:
#     ./scripts/install.sh
############################################################################

CURR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${CURR_DIR}")"

source "${CURR_DIR}/_utils.sh"

main() {
  print_heading "Installing workspace: ${REPO_ROOT}"

  # Upgrade wheel package to ensure we can build binary packages efficiently
  # This is particularly important for packages with C extensions
  pip install --upgrade wheel

  # Install development tools (black, isort, ruff, pyright, etc.)
  # These are defined in [project.optional-dependencies] section of pyproject.toml
  print_heading "Installing validation dependencies"
  pip install .[dev]

  # Install all runtime dependencies from the pinned requirements.txt
  # --no-deps: Skip dependency resolution since requirements.txt is already resolved
  # --no-cache: Force fresh install to avoid any cached package issues
  # This file is auto-generated by pip-compile via ./scripts/upgrade.sh
  print_heading "Installing requirements.txt"
  pip install --no-deps \
    -r "${REPO_ROOT}/requirements.txt" --no-cache

  # Install the workspace package itself in editable mode
  # This makes the package importable so that:
  # 1. IDE (VS Code) can provide autocomplete and import recognition
  # 2. Validation tools (pyright, ruff, etc.) can analyze the code
  # 3. You can modify source code without reinstalling
  print_heading "Installing workspace ${REPO_ROOT}"
  pip install --editable "${REPO_ROOT}"
}

main "$@"
