import json
import re
import time
import uuid
from collections import defaultdict
from datetime import datetime, timedelta, timezone

from sqlalchemy import Table
from sqlalchemy.orm import Session, declarative_base

import db
from api.schemas.admin.conversation import ConversationPreview
from services import message_service, user_service
from services.admin_service.schema import UserSessionPreview
from services.message_service import (
    get_conversations_by_users,
    get_messages_by_conversation,
)
from services.project_service import get_project, replace_project_channel_identifiers
from services.user_service import get_users_by_account_id
from utils import secret
from utils.log import logger

TEST_PHONE_NUMBERS = ["+16692463752", "+14384973894"]
MOCK_USER_PREFIX = "mock-user"


def _include_conversation_preview(message: db.Message, max_age: int) -> bool:
    """
    An internal filter function that determines whether a conversation should be included in get_inbox_conversations
    The conversation cannot be older than max_age, if specified.

    Args:
        message: The conversation's last message
        max_age: age limit in minutes. 0 by default (meaning no limit) as provided in __init__.py
    Returns:
        bool: whether to include the conversation
    """
    if max_age:
        return message.created_at >= datetime.now(timezone.utc) - timedelta(
            minutes=max_age
        )

    return True


def get_conversation_by_id(
    session: Session,
    conversation_id: uuid.UUID,
) -> db.Conversation | None:
    conversation_repository = db.ConversationRepository(session)
    conversation = conversation_repository.get_conversation_by_id(conversation_id)
    return conversation


def list_user_sessions_in_account(
    account_id: uuid.UUID,
    page: int,
    page_size: int,
    db_session: Session,
) -> tuple[int, list[UserSessionPreview]]:
    message_repository = db.MessageRepository(db_session)

    def is_test_message(message: db.Message) -> bool:
        if message.body.get("metadata", {}).get("testing"):
            return True
        if message.body.get("sender_identifier", "").startswith(MOCK_USER_PREFIX):
            return True
        return False

    # Retrieve all user sessions on the requested page
    account_users = user_service.get_users_by_account_id(db_session, account_id)
    account_users_ids = [user.id for user in account_users]
    total, conversations = message_service.get_conversations_by_users(
        db_session, page, page_size, account_users_ids
    )
    # Build the session previews
    user_session_previews = [
        UserSessionPreview(
            user_session=conversation,
            last_message=message_repository.get_last_user_message_by_conversation(
                conversation.id
            )
            or message_repository.get_last_message_by_conversation(conversation.id),
            message_count=message_repository.get_message_count_by_conversation(
                conversation.id
            ),
        )
        for conversation in conversations
    ]
    # Filter out the test sessions
    selected_session_previews = []
    for preview in user_session_previews:
        message = preview.last_message
        if message and is_test_message(message):
            # drop this session
            continue
        selected_session_previews.append(preview)

    return total, selected_session_previews


def get_inbox_conversations(
    session: Session, account_id: uuid.UUID, max_age: int, page: int, page_size: int
) -> tuple[int, list[ConversationPreview]]:
    # Get users associated with the account
    users = get_users_by_account_id(session, account_id=account_id)

    # Get all conversations involving a user with the account id
    total_conversations, conversations = get_conversations_by_users(
        session, page, page_size, user_ids=list(map(lambda user: user.id, users))
    )
    conversation_user_ids = list(
        map(lambda conv: (conv.id, conv.user_id), conversations)
    )

    message_counts: dict[uuid.UUID, int] = {}
    last_messages: dict[uuid.UUID, db.Message] = {}
    escalated_conversations: dict[uuid.UUID, bool] = {}

    message_repository = db.MessageRepository(session)
    for id, _ in conversation_user_ids:
        # Get most recent message for each conversation generated by a user
        last_message = message_repository.get_last_user_message_by_conversation(id)

        # If there are no messages, skip this conversation
        if last_message is None or last_message.body is None:
            continue

        # If the last message is from the testing phone number, skip this conversation
        if (
            last_message.body.get("sender_identifier", "") == "+16692463752"
            or last_message.body.get("sender_identifier", "") == "+14384973894"
        ):
            continue

        # If the last message ends with "latest" or "staging", skip this conversation
        if not last_message.body.get("text"):
            continue

        last_message_text = last_message.body.get("text", {}).get("body", "").lower()
        if re.search(r"\b(?:latest|staging)\b$", last_message_text):
            continue

        last_messages[id] = last_message

        # Get most number of messages for each conversation
        message_counts[id] = message_repository.get_message_count_by_conversation(id)

        # Check if the conversation is escalated
        is_escalated = message_repository.is_conversation_escalated(id)

        escalated_conversations[id] = is_escalated

    # Filter conversations by recency of last message, and sort descending by created_at
    conversation_previews = sorted(
        filter(
            lambda preview: _include_conversation_preview(preview[3], max_age),
            [
                (
                    id,
                    user_id,
                    message_counts[id],
                    last_messages[id],
                    last_messages[id].created_at,
                    escalated_conversations[id],
                )
                for id, user_id in conversation_user_ids
                if id in message_counts and id in last_messages
            ],
        ),
        key=lambda preview: preview[4],
        reverse=True,
    )

    def _get_last_message_details(message: db.Message):
        """Extracts relevant message details including text, media, channel, sender, recipient, and broker."""
        last_message_text = ""

        # Extract text if available
        if message.body.get("text") is not None:
            last_message_text = message.body.get("text", {}).get("body", "")
        # Extract media URL if text is unavailable
        elif message.body.get("media") is not None:
            last_message_text = message.body.get("media", {}).get("url", "")

        channel = message.body.get("channel", "")
        sender_identifier = message.body.get("sender_identifier", "")
        recipient_identifier = message.body.get("recipient_identifier", "")
        broker = message.body.get("broker", None)

        return (
            last_message_text,
            channel,
            sender_identifier,
            recipient_identifier,
            broker,
        )  # type: ignore

    # Reformat conversations
    inbox: list[ConversationPreview] = [
        ConversationPreview(
            id=str(conversation[0]),
            user_id=str(conversation[1]),
            num_messages=conversation[2],
            last_message_text=last_text,
            channel=channel,
            sender_identifier=sender_identifier,
            recipient_identifier=recipient_identifier,
            broker=broker,
            created_at=conversation[4],
            is_escalated=conversation[5],
        )
        for conversation in conversation_previews
        for last_text, channel, sender_identifier, recipient_identifier, broker in [
            _get_last_message_details(conversation[3])
        ]
    ]

    return total_conversations, inbox


def get_conversation_messages(
    session: Session,
    account_id: uuid.UUID,
    conversation_id: uuid.UUID,
    sort_desc: bool = False,
) -> list[db.Message]:
    conversation_repository = db.ConversationRepository(session)
    user_repository = db.UserRepository(session)

    """
    First we need to ensure that the requesting Account can access this Conversation.
    For example, if a Client A's Admin types in a random UUID that corresponds to a Conversation
    from Client B, A's Admin should not be able to access it.
    """

    # Get the Account ID associated with the Conversation ID
    conversation = conversation_repository.get_conversation_by_id(conversation_id)

    if not conversation:
        raise ValueError("Conversation not found.")

    user = user_repository.get_user_by_id(conversation.user_id)

    if not user:
        raise ValueError("User not found.")

    # If the Account IDs do not match, the Admin does not have access to this Conversation
    if user.account_id != account_id:
        raise ValueError(
            "Account ID of Conversation and requesting Account do not match."
        )

    # Requesting Account matches Account associated with Conversation, so get messages and return
    messages = get_messages_by_conversation(session, conversation_id=conversation_id)

    # Sort messages by timestamp
    messages.sort(
        key=lambda m: (
            0 if isinstance(m, str) else 1,
            (
                m
                if isinstance(m, str)
                else m.body.get("timestamp", str(m.created_at or datetime.min))
            ),
        ),
        reverse=sort_desc,
    )

    return messages


def get_conversation_ids_by_message_ids(
    session: Session,
    message_ids: list[uuid.UUID],
) -> dict[uuid.UUID, str]:
    """
    Retrieves the conversation ID associated with each given message ID.

    Args:
        session (Session): The database session.
        message_ids (list[uuid.UUID]): A list of unique identifiers for the requested messages.

    Returns:
        dict[uuid.UUID, str]: A dictionary mapping each message ID to its conversation ID.

    Raises:
        ValueError: If a message ID does not have an associated conversation ID.
    """
    message_repository = db.MessageRepository(session)

    # Create a mapping of message IDs to conversation IDs
    result = {}
    for message_id in message_ids:
        conversation_id = message_repository.get_conversation_id_by_message_id(
            message_id=message_id
        )
        if not conversation_id:
            raise ValueError(f"Conversation not found for message ID: {message_id}")
        result[message_id] = str(conversation_id)

    return result


def get_messages_by_conversation_id(
    session: Session, account_id: uuid.UUID, conversation_id: uuid.UUID
) -> list[db.Message]:
    conversation_repository = db.ConversationRepository(session)
    user_repository = db.UserRepository(session)
    feedback_repository = db.FeedbackRepository(session)

    # Get the Account ID associated with the Conversation ID
    conversation = conversation_repository.get_conversation_by_id(conversation_id)

    if not conversation:
        raise ValueError("Conversation not found.")

    user = user_repository.get_user_by_id(conversation.user_id)

    if not user:
        raise ValueError("User not found.")

    # If the Account IDs do not match, the Admin does not have access to this Conversation
    if user.account_id != account_id:
        raise ValueError(
            "Account ID of Conversation and requesting Account do not match."
        )

    messages = get_messages_by_conversation(session, conversation_id=conversation_id)

    message_ids = [message.id for message in messages]
    feedback_for_messages = feedback_repository.get_feedback_by_message_ids(message_ids)

    message_id_to_feedback = defaultdict(list)
    for feedback in feedback_for_messages:
        message_id_to_feedback[feedback.message_id].append(feedback)

    for message in messages:
        message.feedback = message_id_to_feedback[message.id]

    return messages


def get_knowledge_base(session: Session, account_name: str) -> list:
    Base = declarative_base()

    if not account_name:
        raise ValueError("Account not found.")

    try:
        # Dynamically get the table name
        table_name = f"{account_name}_knowledge_agno"

        # Fetch the table dynamically by reflecting the table from the database schema
        knowledge_table = Table(
            table_name, Base.metadata, autoload_with=session.bind, schema="ai"
        )

        # Query the dynamically selected table
        knowledge_base_list = session.query(knowledge_table).all()

        # Map results into a list of dictionaries
        knowledge_base_list = [
            {
                "content": item.content,
                "id": item.id,
                "name": item.name,
                "created_at": item.created_at,
            }
            for item in knowledge_base_list
        ]

        return knowledge_base_list

    except Exception as e:
        logger.error(f"Unable to get knowledge base: {e}")
        raise RuntimeError("Unable to get knowledge base.") from e


def get_knowledge_base_by_document_id(
    session: Session, account_name: str, document_id: str
) -> dict:
    knowledge = get_knowledge_base(session, account_name)
    if not knowledge:
        return {}
    for item in knowledge:
        if item["id"] == document_id:
            return item
    return {}


def update_knowledge(
    session: Session, account_name: str, knowledge_id: str, content: str
) -> None:
    """
    Update AI knowledge content by the knowledge ID.

    Args:
        session (Session): The session to use.
        account_name (str): The account name to retrieve the AI knowledge for.
        knowledge_id (str): The ID of the knowledge to update.
        content (str): The new content to update the AI knowledge with.

    Returns:
        KnowledgeBase | None: The updated AI knowledge or None if no such knowledge is found.
    """
    Base = declarative_base()

    if not account_name:
        raise ValueError("Account not found.")

    try:
        table_name = f"{account_name}_knowledge_agno"

        knowledge_table = Table(
            table_name, Base.metadata, autoload_with=session.bind, schema="ai"
        )

        result = session.execute(
            knowledge_table.update()
            .where(knowledge_table.c.id == knowledge_id)
            .values(content=content)
        )

        if result.rowcount == 0:
            raise ValueError("Knowledge not found.")

        session.commit()
        print("Knowledge updated successfully.")

    except Exception as e:
        logger.error(f"Unable to update knowledge by ID: {e}")
        raise RuntimeError("Unable to update knowledge by ID.") from e


def _project_name_to_ig_access_token_key(project_name: str) -> str:
    return f"{project_name.upper()}_INSTAGRAM_ACCESS_TOKEN"


def _ig_user_id_to_ig_project_name_key(user_id: str) -> str:
    return f"INSTAGRAM_USER_{user_id}_PROJECT_KEY"


def _parse_ig_project_secret_value(secret_value) -> dict:
    try:
        if not isinstance(secret_value, dict):
            secret_dict = json.loads(secret_value)
        else:
            secret_dict = secret_value

        return secret_dict
    except Exception as e:
        logger.error(f"Unable to parse project secret value: {e}")
        raise RuntimeError("Unable to parse project secret value.") from e


def get_instagram_connected(session: Session, project_id: uuid.UUID) -> bool:
    project = get_project(session, project_id)
    if not project:
        raise ValueError("Project not found.")

    project_secret_key = _project_name_to_ig_access_token_key(project.name)
    try:
        # if successful, then the key exists, and hence the project is connected
        secret.get_client_secret(project_secret_key)
        return True
    except KeyError:
        # if the key does not exist, then the project is not connected
        return False
    except Exception as e:
        # if any other error occurs, log and raise
        logger.info(f"Unable to get Instagram access token: {e}")
        raise RuntimeError(f"Unable to get Instagram access token: {e}")


def get_instagram_username(session: Session, project_id: uuid.UUID) -> str:
    project = get_project(session, project_id)
    if not project:
        raise ValueError("Project not found.")

    project_secret_key = _project_name_to_ig_access_token_key(project.name)

    # Ensure the project is connected to Instagram
    try:
        # if successful, then the key exists, and hence the project is connected
        secret_value = secret.get_client_secret(project_secret_key)
    except KeyError:
        # if the key does not exist, then the project is not connected
        # log and raise
        logger.info("Project is not connected to Instagram.")
        raise ValueError("Project is not connected to Instagram.")
    except Exception as e:
        # if any other error occurs, log and raise
        logger.info(f"Unable to get Instagram access token: {e}")
        raise RuntimeError(f"Unable to get Instagram access token: {e}")

    try:
        secret_dict = _parse_ig_project_secret_value(secret_value)
    except RuntimeError as e:
        logger.error(f"Unable to parse project secret value: {e}")
        raise RuntimeError("Unable to parse project secret value.") from e

    return secret_dict.get("username", "")


def set_instagram_access_token(
    session: Session,
    project_id: uuid.UUID,
    access_token: str,
    user_id: str,
    username: str,
) -> None:
    """
    Add both project and user secrets atomically, with rollback attempt if necessary
    """
    project = get_project(session, project_id)
    if not project:
        raise ValueError("Project not found.")

    project_secret_key = _project_name_to_ig_access_token_key(project.name)
    project_secret_value = json.dumps(
        {"access_token": access_token, "user_id": user_id, "username": username}
    )

    user_secret_key = _ig_user_id_to_ig_project_name_key(user_id)
    user_secret_value = project_secret_key

    # Add secrets, and rollback if necessary
    try:
        # Attempt to add both secrets one by one
        secret.add_client_secret(project_secret_key, project_secret_value)

        # Temporary solution to try to avoid versioning errors
        time.sleep(5)

        try:
            secret.add_client_secret(user_secret_key, user_secret_value)
        except Exception as add_e:
            # Rollback first secret if second secret fails
            logger.error(
                f"Unable to add user secret, try rolling back project secret: {add_e}"
            )
            try:
                secret.remove_client_secret(project_secret_key)
            except Exception as rollback_e:
                logger.error(f"Unable to roll back project secret: {rollback_e}")
                raise RuntimeError(
                    "Unable to roll back project secret."
                ) from rollback_e
            raise RuntimeError(
                "Unable to add user secret, succsesfully rolled back project secret."
            ) from add_e
    except KeyError as e:
        # If the project_secret_key already exists, check whether the user_secret_key exists
        logger.info(e)
        try:
            # if user_secret_key exists as well, then the project is already connected
            secret.get_client_secret(user_secret_key)
        except KeyError as get_e:
            # If the project_secret_key exists but the user_secret_key does not, something went wrong
            logger.error(
                f"Inconsistent state, project secret exists but user secret does not: {get_e}"
            )
            raise RuntimeError(
                "Inconsistent state, project secret exists but user secret does not."
            ) from get_e
        except Exception as get_e:
            # Log error and raise
            logger.error(f"Unable to verify if user secret exists : {get_e}")
            raise RuntimeError("Unable to verify if user secret exists.") from get_e
    except Exception as e:
        logger.error(f"Unable to set Instagram access token: {e}")
        raise RuntimeError("Unable to set Instagram access token.") from e

    try:
        channel_identifiers = project.channel_identifiers

        # Modifying the existing array does not work, copy to new array instead
        new_channel_identifiers = []
        if channel_identifiers:
            for channel_identifier in channel_identifiers:
                new_channel_identifiers.append(channel_identifier)

        # Add the new channel identifier for the connected instagram account
        instagram_channel_identifier = f"instagram:{user_id}"
        if instagram_channel_identifier not in new_channel_identifiers:
            new_channel_identifiers.append(instagram_channel_identifier)
        replace_project_channel_identifiers(
            session, project_id, new_channel_identifiers
        )
    except Exception as e:
        logger.error(f"Unable to update project channel identifiers: {e}")
        raise RuntimeError("Unable to update project channel identifiers.") from e


def remove_instagram_access_token(session: Session, project_id: uuid.UUID) -> None:
    """
    Remove both project and user secrets using the project secret key
    """
    project = get_project(session, project_id)
    if not project:
        raise ValueError("Project not found.")

    project_secret_key = _project_name_to_ig_access_token_key(project.name)

    try:
        secret_value = secret.get_client_secret(project_secret_key)
    except KeyError as e:
        # if the key does not exist, then the project is not connected
        logger.info(e)
        return
    except Exception as e:
        logger.error(f"Unable to remove Instagram access token: {e}")
        raise RuntimeError(f"Unable to remove Instagram access token: {e}")

    try:
        secret_dict = _parse_ig_project_secret_value(secret_value)
    except RuntimeError as e:
        logger.error(f"Unable to parse project secret value: {e}")
        raise RuntimeError("Unable to parse project secret value.") from e

    ig_user_id = secret_dict.get("user_id", "")
    if not ig_user_id:
        raise RuntimeError("Instagram user ID not found in project secret.")

    user_secret_key = _ig_user_id_to_ig_project_name_key(ig_user_id)

    try:
        # Remove both secrets
        secret.remove_client_secret(project_secret_key)

        # Temporary solution to try to avoid versioning errors
        time.sleep(5)

        try:
            secret.remove_client_secret(user_secret_key)
        except KeyError as e:
            # if the user_secret_key does not exist, log and continue
            logger.info(
                f"user secret {user_secret_key} does not exist, continuing: {e}"
            )
        except Exception as e:
            logger.error(f"Unable to remove user secret: {e}")
            raise RuntimeError("Unable to remove user secret.") from e
    except KeyError as e:
        # If the project_secret_key does not exist, check whether the user_secret_key exists
        logger.info(
            f"project secret does not exist, checking whether user secret exists: {e}"
        )

        try:
            secret.get_client_secret(user_secret_key)
        except KeyError as get_e:
            # Neither keys exists, so the project was already disconnected
            logger.info(
                f"Neither project secret nor user secret exist, continuing: {get_e}"
            )
            return
        except Exception as get_e:
            # Log error and raise
            logger.error(f"Unable to verify if user secret exists: {get_e}")
            raise RuntimeError("Unable to verify if user secret exists.") from get_e

        # if user_secret_key exists, log data inconsistency
        logger.error(
            "Inconsistent state, user secret exists but project secret does not."
        )
        raise RuntimeError(
            "Inconsistent state, user secret exists but project secret does not."
        )
    except Exception as e:
        logger.error(f"Unable to remove Instagram access token: {e}")
        raise RuntimeError("Unable to remove Instagram access token.") from e


def deauthorize_instagram_access_token(session: Session, ig_user_id: str) -> None:
    """
    Remove both project and user secrets using the user secret key
    """
    if not ig_user_id:
        raise ValueError("Instagram user ID is required.")

    user_secret_key = _ig_user_id_to_ig_project_name_key(ig_user_id)

    try:
        project_secret_key = secret.get_client_secret(user_secret_key)
    except KeyError as e:
        # if the key does not exist, then the project is not connected
        logger.info(e)
        return
    except Exception as e:
        logger.error(f"Unable to deauthorize Instagram access token: {e}")
        raise RuntimeError(f"Unable to deauthorize Instagram access token: {e}")

    try:
        # Remove both secrets
        secret.remove_client_secret(project_secret_key)

        # Temporary solution to try to avoid versioning errors
        time.sleep(5)

        try:
            secret.remove_client_secret(user_secret_key)
        except KeyError as e:
            # if the user_secret_key does not exist, log and continue
            logger.info(
                f"user secret {user_secret_key} does not exist, continuing: {e}"
            )
        except Exception as e:
            logger.error(f"Unable to remove user secret: {e}")
            raise RuntimeError("Unable to remove user secret.") from e
    except KeyError as e:
        # If the project_secret_key does not exist, check whether the user_secret_key exists
        logger.info(
            f"project secret does not exist, checking whether user secret exists: {e}"
        )

        try:
            # if user_secret_key exists, log data inconsistency
            secret.get_client_secret(user_secret_key)
        except KeyError as get_e:
            # Neither keys exists, so the project was already disconnected
            logger.info(
                f"Neither project secret nor user secret exist, continuing: {get_e}"
            )
            return
        except Exception as get_e:
            # Log error and raise
            logger.error(f"Unable to verify if user secret exists: {get_e}")
            raise RuntimeError("Unable to verify if user secret exists.") from get_e

        # if user_secret_key exists, log data inconsistency
        logger.error(
            "Inconsistent state, user secret exists but project secret does not."
        )
        raise RuntimeError(
            "Inconsistent state, user secret exists but project secret does not."
        )
    except Exception as e:
        logger.error(f"Unable to remove Instagram access token: {e}")
        raise RuntimeError("Unable to remove Instagram access token.") from e


def get_session_count_by_user_and_status(
    session: Session,
    user_ids: list[uuid.UUID],
    status: db.ConversationStatus | None = None,
) -> int:
    conversation_repository = db.ConversationRepository(session)
    return conversation_repository.get_session_count_by_user_and_status(
        user_ids, status
    )


def get_escalated_session_count_by_users(
    session: Session,
    user_ids: list[uuid.UUID],
) -> int:
    conversation_repository = db.ConversationRepository(session)
    message_repository = db.MessageRepository(session)

    conversation_ids = conversation_repository.get_conversation_ids_by_user_ids(
        user_ids
    )
    escalated_conversation_count = message_repository.get_escalated_conversation_count(
        conversation_ids
    )
    return escalated_conversation_count
