# Warning: changing the name will reset the action run number / build number.
name: Create build

on:
  push:
    branches:
      - "main"

# Ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      BUILD_TAG: ${{ steps.set_build_tag.outputs.BUILD_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set BUILD_TAG
        id: set_build_tag
        run: echo "BUILD_TAG=build-${{ github.run_number }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Display build information
        run: |
          echo "Current run number: ${{ github.run_number }}"
          echo "Build tag: ${{ steps.set_build_tag.outputs.BUILD_TAG }}"

      - name: Push Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ steps.set_build_tag.outputs.BUILD_TAG }} -m "Build ${{ github.run_number }}"
          git push origin ${{ steps.set_build_tag.outputs.BUILD_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Updated image definitions file generation
      - name: Create image definition files
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pal-mono
          UNIQUE_IMAGE_URL: ${{ steps.login-ecr.outputs.registry }}/pal-mono:${{ steps.set_build_tag.outputs.BUILD_TAG }}
        run: |
          # Function to create image definition files for a given stage
          create_image_definitions() {
            local stage=$1
            CONTAINER_NAME_APP="${ECR_REPOSITORY}-${stage}-app"
            CONTAINER_NAME_API="${ECR_REPOSITORY}-${stage}-api"
            
            printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_APP $UNIQUE_IMAGE_URL > imagedefinitions_${stage}_app.json
            printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_API $UNIQUE_IMAGE_URL > imagedefinitions_${stage}_api.json
            
            echo "Created imagedefinitions_${stage}_app.json and imagedefinitions_${stage}_api.json"
            echo "Contents of imagedefinitions_${stage}_app.json:"
            cat imagedefinitions_${stage}_app.json
            echo "Contents of imagedefinitions_${stage}_api.json:"
            cat imagedefinitions_${stage}_api.json
          }
          
          # Create image definition files for each stage
          create_image_definitions "lat"
          create_image_definitions "stg"
          create_image_definitions "prd"
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pal-mono
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }} \
            --build-arg IMAGEDEFINITIONS_LAT_APP_FILE=imagedefinitions_lat_app.json \
            --build-arg IMAGEDEFINITIONS_LAT_API_FILE=imagedefinitions_lat_api.json \
            --build-arg IMAGEDEFINITIONS_STG_APP_FILE=imagedefinitions_stg_app.json \
            --build-arg IMAGEDEFINITIONS_STG_API_FILE=imagedefinitions_stg_api.json \
            --build-arg IMAGEDEFINITIONS_PRD_APP_FILE=imagedefinitions_prd_app.json \
            --build-arg IMAGEDEFINITIONS_PRD_API_FILE=imagedefinitions_prd_api.json .
            
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }}
          echo "Pushed image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }}"

      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
          message: |
            Deployment status: ${{ job.status }}
            Run number: ${{ github.run_number }}
            Build tag: ${{ steps.set_build_tag.outputs.BUILD_TAG }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_BUILD }}