# Warning: changing the name will reset the action run number / build number.
name: Create build

on:
  push:
    branches:
      - "main"

# Ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      BUILD_TAG: ${{ steps.set_build_tag.outputs.BUILD_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set BUILD_TAG
        id: set_build_tag
        run: echo "BUILD_TAG=build-${{ github.run_number }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Display build information
        run: |
          echo "Current run number: ${{ github.run_number }}"
          echo "Build tag: ${{ steps.set_build_tag.outputs.BUILD_TAG }}"

      - name: Push Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ steps.set_build_tag.outputs.BUILD_TAG }} -m "Build ${{ github.run_number }}"
          git push origin ${{ steps.set_build_tag.outputs.BUILD_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pal-mono
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }}
          echo "Pushed image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set_build_tag.outputs.BUILD_TAG }}"

      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
          message: |
            Deployment status: ${{ job.status }}
            Run number: ${{ github.run_number }}
            Build tag: ${{ steps.set_build_tag.outputs.BUILD_TAG }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Trigger Create Release Workflow for Latest
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'create-release.yml',
              ref: 'main',
              inputs: {
                stage: 'lat',
                build_tag: '${{ steps.set_build_tag.outputs.BUILD_TAG }}'
              }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call_create_release:
    needs: create_build
    permissions:
      contents: write
    uses: ./.github/workflows/create-release.yml
    with:
      stage: 'lat'
      build_tag: ${{ needs.create_build.outputs.BUILD_TAG }}
    secrets: inherit