name: Pre commit

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U \
            pip setuptools wheel \
            mypy ruff
          pip install --no-deps -r requirements.txt

      - name: Format with black
        run: |
          black .

      - name: Sort imports with isort
        run: |
          isort .

      - name: Lint with ruff
        run: |
          ruff check .

      # - name: Type-check with mypy
      #   run: |
      #     mypy .

      # If the job fails, send a message to Slack
      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: failure() && github.ref == 'refs/heads/main' && github.event.pull_request.draft == false
        env:
          SLACK_WEBHOOK_URL_BUILD: ${{ secrets.SLACK_WEBHOOK_URL_BUILD }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U \
            pip setuptools wheel \
            mypy ruff
          pip install -r requirements.txt

      - name: Run pytest
        env:
          AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
          AWS_APP_CLIENT_ID: ${{ secrets.AWS_APP_CLIENT_ID }}
          AWS_APP_CLIENT_SECRET: ${{ secrets.AWS_APP_CLIENT_SECRET }}
          MODAL_API_KEY: ${{ secrets.MODAL_API_KEY }}
          ADMIN_CONSOLE_AWS_CLIENT_ID: ${{ secrets.ADMIN_CONSOLE_AWS_CLIENT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ci: true
        run: |
          pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: myapp:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run myapp:${{ github.sha }} echo "Container is running correctly"
        
      # If the build job fails, send a message to Slack
      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: failure() && github.ref == 'refs/heads/main' && github.event.pull_request.draft == false
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_BUILD }}