name: Pre commit

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Create a virtual environment and activate it
      - name: Set up virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies in virtual environment
        run: |
          .venv/bin/python -m pip install --upgrade pip setuptools wheel
          .venv/bin/python -m pip install uv==0.1.3
          .venv/bin/uv pip install black==24.8.0 isort==5.13.2 ruff==0.6.2 pyright==1.1.382
          .venv/bin/uv pip install --no-cache -r requirements.txt

      - name: Format check with black
        run: |
          .venv/bin/black . --check --diff

      - name: Lint with ruff
        run: |
          .venv/bin/ruff check .

      - name: Sort imports with isort
        run: |
          .venv/bin/isort .

      - name: Set PATHS for pyright
        run: |
          echo "${PWD}/.venv/bin" >> $GITHUB_PATH

      - name: Type-check with pyright
        run: |
          .venv/bin/pyright .

      # If the job fails, send a message to Slack
      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: failure() && github.ref == 'refs/heads/main' && github.event.pull_request.draft == false
        env:
          SLACK_WEBHOOK_URL_BUILD: ${{ secrets.SLACK_WEBHOOK_URL_BUILD }}

  pre-coverage:
    runs-on: ubuntu-latest

    outputs:
      main_coverage: ${{ steps.get_main_coverage.outputs.coverage }}

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Create a virtual environment and activate it
      - name: Set up virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies in virtual environment
        run: |
          .venv/bin/python -m pip install --upgrade pip setuptools wheel
          .venv/bin/pip install uv
          .venv/bin/uv pip install -r requirements.txt
      
      - name: Run main pytest report
        id: get_main_coverage
        run: |
          echo "coverage<<EOF" >> $GITHUB_OUTPUT
          echo "$(.venv/bin/pytest --cov=. | awk '{printf "%s\\n", $0}')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
  test:
    if: ${{ false }}  # This will prevent the job from running
    runs-on: ubuntu-latest

    needs: pre-coverage

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Create a virtual environment and activate it
      - name: Set up virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies in virtual environment
        run: |
          .venv/bin/python -m pip install --upgrade pip setuptools wheel
          .venv/bin/python -m pip install uv
          .venv/bin/uv pip install black==24.8.0 isort==5.13.2 ruff==0.6.2 pyright==1.1.382
          .venv/bin/uv pip install --no-cache -r requirements.txt
      
      - name: Run new pytest report
        id: get_new_coverage
        run: |
          echo "coverage<<EOF" >> $GITHUB_OUTPUT
          echo "$(.venv/bin/pytest --cov=. | awk '{printf "%s\\n", $0}')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      
      - name: Get coverage warnings
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        id: get_coverage_warnings
        run: |
          echo "warnings<<EOF" >> $GITHUB_OUTPUT
          echo "$(.venv/bin/python ./.github/workflows/coverage_analysis.py '${{ needs.pre-coverage.outputs.main_coverage }}' '${{ steps.get_new_coverage.outputs.coverage }}' ${ALL_CHANGED_FILES[@]} | awk '{printf "%s\\n", $0}')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: PR testing coverage comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.get_coverage_warnings.outputs.warnings }}<details><summary>Code coverage</summary>\n\n```\n${{ steps.get_new_coverage.outputs.coverage }}```\n\n</details>"
            })

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: myapp:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run myapp:${{ github.sha }} echo "Container is running correctly"

      # If the build job fails, send a message to Slack
      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: failure() && github.ref == 'refs/heads/main' && github.event.pull_request.draft == false
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_BUILD }}