name: Release

on:
  push:
    branches:
      - "main"

env:
  BUILD_TAG: build-${{ github.run_number }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Display build information
        run: |
          echo "Current run number: ${{ github.run_number }}"
          echo "Build tag: ${{ env.BUILD_TAG }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pal-mono
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.BUILD_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.BUILD_TAG }}
          echo "Pushed image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.BUILD_TAG }}"

      - name: Create Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ env.BUILD_TAG }} -m "Build ${{ github.run_number }}"
          git push origin ${{ env.BUILD_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
          message: |
            Deployment status: ${{ job.status }}
            Run number: ${{ github.run_number }}
            Build tag: ${{ env.BUILD_TAG }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}