name: Validate and Build
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
    branches:
      - "main"

jobs:
  validate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U \
            pip setuptools wheel \
            mypy ruff
          pip install --no-deps -r requirements.txt
      - name: Format with black
        run: |
          black .
      - name: Sort imports with isort
        run: |
          isort .
      - name: Lint with ruff
        run: |
          ruff check .
      # - name: Type-check with mypy
      #   run: |
      #     mypy .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: myapp:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        run: |
          docker run myapp:${{ github.sha }} echo "Container is running correctly"

  notify:
    needs: [validate, build]
    if: failure() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/slack-notify.yml
    secrets: inherit